//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.16 at 08:54:58 PM EDT 
//


package org.fpml._2009.fpml_4_7;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Physically settled leg of a physically settled Bullion Transaction.
 * 
 * <p>Java class for BullionPhysicalLeg complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BullionPhysicalLeg">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.fpml.org/2009/FpML-4-7}PhysicalLeg">
 *       &lt;sequence>
 *         &lt;element name="bullionType" type="{http://www.fpml.org/2009/FpML-4-7}BullionTypeEnum"/>
 *         &lt;element name="deliveryLocation" type="{http://www.fpml.org/2009/FpML-4-7}BullionDeliveryLocation"/>
 *         &lt;group ref="{http://www.fpml.org/2009/FpML-4-7}CommodityFixedPhysicalQuantity.model"/>
 *         &lt;element name="settlementDate" type="{http://www.fpml.org/2009/FpML-4-7}AdjustableOrRelativeDate"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BullionPhysicalLeg", propOrder = {
    "bullionType",
    "deliveryLocation",
    "physicalQuantity",
    "physicalQuantitySchedule",
    "totalPhysicalQuantity",
    "settlementDate"
})
public class BullionPhysicalLeg
    extends PhysicalLeg
{

    @XmlElement(required = true)
    protected BullionTypeEnum bullionType;
    @XmlElement(required = true)
    protected BullionDeliveryLocation deliveryLocation;
    protected CommodityNotionalQuantity physicalQuantity;
    protected CommodityPhysicalQuantitySchedule physicalQuantitySchedule;
    protected UnitQuantity totalPhysicalQuantity;
    @XmlElement(required = true)
    protected AdjustableOrRelativeDate settlementDate;

    /**
     * Gets the value of the bullionType property.
     * 
     * @return
     *     possible object is
     *     {@link BullionTypeEnum }
     *     
     */
    public BullionTypeEnum getBullionType() {
        return bullionType;
    }

    /**
     * Sets the value of the bullionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BullionTypeEnum }
     *     
     */
    public void setBullionType(BullionTypeEnum value) {
        this.bullionType = value;
    }

    /**
     * Gets the value of the deliveryLocation property.
     * 
     * @return
     *     possible object is
     *     {@link BullionDeliveryLocation }
     *     
     */
    public BullionDeliveryLocation getDeliveryLocation() {
        return deliveryLocation;
    }

    /**
     * Sets the value of the deliveryLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link BullionDeliveryLocation }
     *     
     */
    public void setDeliveryLocation(BullionDeliveryLocation value) {
        this.deliveryLocation = value;
    }

    /**
     * Gets the value of the physicalQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link CommodityNotionalQuantity }
     *     
     */
    public CommodityNotionalQuantity getPhysicalQuantity() {
        return physicalQuantity;
    }

    /**
     * Sets the value of the physicalQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommodityNotionalQuantity }
     *     
     */
    public void setPhysicalQuantity(CommodityNotionalQuantity value) {
        this.physicalQuantity = value;
    }

    /**
     * Gets the value of the physicalQuantitySchedule property.
     * 
     * @return
     *     possible object is
     *     {@link CommodityPhysicalQuantitySchedule }
     *     
     */
    public CommodityPhysicalQuantitySchedule getPhysicalQuantitySchedule() {
        return physicalQuantitySchedule;
    }

    /**
     * Sets the value of the physicalQuantitySchedule property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommodityPhysicalQuantitySchedule }
     *     
     */
    public void setPhysicalQuantitySchedule(CommodityPhysicalQuantitySchedule value) {
        this.physicalQuantitySchedule = value;
    }

    /**
     * Gets the value of the totalPhysicalQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link UnitQuantity }
     *     
     */
    public UnitQuantity getTotalPhysicalQuantity() {
        return totalPhysicalQuantity;
    }

    /**
     * Sets the value of the totalPhysicalQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnitQuantity }
     *     
     */
    public void setTotalPhysicalQuantity(UnitQuantity value) {
        this.totalPhysicalQuantity = value;
    }

    /**
     * Gets the value of the settlementDate property.
     * 
     * @return
     *     possible object is
     *     {@link AdjustableOrRelativeDate }
     *     
     */
    public AdjustableOrRelativeDate getSettlementDate() {
        return settlementDate;
    }

    /**
     * Sets the value of the settlementDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdjustableOrRelativeDate }
     *     
     */
    public void setSettlementDate(AdjustableOrRelativeDate value) {
        this.settlementDate = value;
    }

}
