//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.16 at 08:54:58 PM EDT 
//


package org.fpml._2009.fpml_4_7;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * Commodity Swap.
 * 
 * <p>Java class for CommoditySwap complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CommoditySwap">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.fpml.org/2009/FpML-4-7}Product">
 *       &lt;sequence>
 *         &lt;element name="effectiveDate" type="{http://www.fpml.org/2009/FpML-4-7}AdjustableOrRelativeDate"/>
 *         &lt;element name="terminationDate" type="{http://www.fpml.org/2009/FpML-4-7}AdjustableOrRelativeDate"/>
 *         &lt;element name="settlementCurrency" type="{http://www.fpml.org/2009/FpML-4-7}IdentifiedCurrency"/>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element name="fixedLeg" type="{http://www.fpml.org/2009/FpML-4-7}FixedPriceLeg"/>
 *           &lt;element name="floatingLeg" type="{http://www.fpml.org/2009/FpML-4-7}FloatingPriceLeg"/>
 *           &lt;element name="coalPhysicalLeg" type="{http://www.fpml.org/2009/FpML-4-7}CoalPhysicalLeg"/>
 *           &lt;element name="electricityPhysicalLeg" type="{http://www.fpml.org/2009/FpML-4-7}ElectricityPhysicalLeg"/>
 *           &lt;element name="gasPhysicalLeg" type="{http://www.fpml.org/2009/FpML-4-7}GasPhysicalLeg"/>
 *           &lt;element name="oilPhysicalLeg" type="{http://www.fpml.org/2009/FpML-4-7}OilPhysicalLeg"/>
 *           &lt;element ref="{http://www.fpml.org/2009/FpML-4-7}additionalCommoditySwapLeg"/>
 *         &lt;/choice>
 *         &lt;group ref="{http://www.fpml.org/2009/FpML-4-7}CommodityContent.model" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CommoditySwap", propOrder = {
    "effectiveDate",
    "terminationDate",
    "settlementCurrency",
    "fixedLegOrFloatingLegOrCoalPhysicalLeg",
    "commonPricing",
    "marketDisruption",
    "settlementDisruption",
    "rounding"
})
public class CommoditySwap
    extends Product
{

    @XmlElement(required = true)
    protected AdjustableOrRelativeDate effectiveDate;
    @XmlElement(required = true)
    protected AdjustableOrRelativeDate terminationDate;
    @XmlElement(required = true)
    protected IdentifiedCurrency settlementCurrency;
    @XmlElements({
        @XmlElement(name = "additionalCommoditySwapLeg"),
        @XmlElement(name = "oilPhysicalLeg", type = OilPhysicalLeg.class),
        @XmlElement(name = "coalPhysicalLeg", type = CoalPhysicalLeg.class),
        @XmlElement(name = "electricityPhysicalLeg", type = ElectricityPhysicalLeg.class),
        @XmlElement(name = "floatingLeg", type = FloatingPriceLeg.class),
        @XmlElement(name = "gasPhysicalLeg", type = GasPhysicalLeg.class),
        @XmlElement(name = "fixedLeg", type = FixedPriceLeg.class)
    })
    protected List<Object> fixedLegOrFloatingLegOrCoalPhysicalLeg;
    protected Boolean commonPricing;
    protected CommodityMarketDisruption marketDisruption;
    protected CommodityBullionSettlementDisruptionEnum settlementDisruption;
    protected Rounding rounding;

    /**
     * Gets the value of the effectiveDate property.
     * 
     * @return
     *     possible object is
     *     {@link AdjustableOrRelativeDate }
     *     
     */
    public AdjustableOrRelativeDate getEffectiveDate() {
        return effectiveDate;
    }

    /**
     * Sets the value of the effectiveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdjustableOrRelativeDate }
     *     
     */
    public void setEffectiveDate(AdjustableOrRelativeDate value) {
        this.effectiveDate = value;
    }

    /**
     * Gets the value of the terminationDate property.
     * 
     * @return
     *     possible object is
     *     {@link AdjustableOrRelativeDate }
     *     
     */
    public AdjustableOrRelativeDate getTerminationDate() {
        return terminationDate;
    }

    /**
     * Sets the value of the terminationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdjustableOrRelativeDate }
     *     
     */
    public void setTerminationDate(AdjustableOrRelativeDate value) {
        this.terminationDate = value;
    }

    /**
     * Gets the value of the settlementCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifiedCurrency }
     *     
     */
    public IdentifiedCurrency getSettlementCurrency() {
        return settlementCurrency;
    }

    /**
     * Sets the value of the settlementCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifiedCurrency }
     *     
     */
    public void setSettlementCurrency(IdentifiedCurrency value) {
        this.settlementCurrency = value;
    }

    /**
     * Gets the value of the fixedLegOrFloatingLegOrCoalPhysicalLeg property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fixedLegOrFloatingLegOrCoalPhysicalLeg property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFixedLegOrFloatingLegOrCoalPhysicalLeg().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * {@link OilPhysicalLeg }
     * {@link CoalPhysicalLeg }
     * {@link ElectricityPhysicalLeg }
     * {@link FloatingPriceLeg }
     * {@link GasPhysicalLeg }
     * {@link FixedPriceLeg }
     * 
     * 
     */
    public List<Object> getFixedLegOrFloatingLegOrCoalPhysicalLeg() {
        if (fixedLegOrFloatingLegOrCoalPhysicalLeg == null) {
            fixedLegOrFloatingLegOrCoalPhysicalLeg = new ArrayList<Object>();
        }
        return this.fixedLegOrFloatingLegOrCoalPhysicalLeg;
    }

    /**
     * Gets the value of the commonPricing property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCommonPricing() {
        return commonPricing;
    }

    /**
     * Sets the value of the commonPricing property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCommonPricing(Boolean value) {
        this.commonPricing = value;
    }

    /**
     * Gets the value of the marketDisruption property.
     * 
     * @return
     *     possible object is
     *     {@link CommodityMarketDisruption }
     *     
     */
    public CommodityMarketDisruption getMarketDisruption() {
        return marketDisruption;
    }

    /**
     * Sets the value of the marketDisruption property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommodityMarketDisruption }
     *     
     */
    public void setMarketDisruption(CommodityMarketDisruption value) {
        this.marketDisruption = value;
    }

    /**
     * Gets the value of the settlementDisruption property.
     * 
     * @return
     *     possible object is
     *     {@link CommodityBullionSettlementDisruptionEnum }
     *     
     */
    public CommodityBullionSettlementDisruptionEnum getSettlementDisruption() {
        return settlementDisruption;
    }

    /**
     * Sets the value of the settlementDisruption property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommodityBullionSettlementDisruptionEnum }
     *     
     */
    public void setSettlementDisruption(CommodityBullionSettlementDisruptionEnum value) {
        this.settlementDisruption = value;
    }

    /**
     * Gets the value of the rounding property.
     * 
     * @return
     *     possible object is
     *     {@link Rounding }
     *     
     */
    public Rounding getRounding() {
        return rounding;
    }

    /**
     * Sets the value of the rounding property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rounding }
     *     
     */
    public void setRounding(Rounding value) {
        this.rounding = value;
    }

}
