//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.16 at 08:55:11 PM EDT 
//


package org.fpml._2009.fpml_4_7;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A complex type to support the credit default swap option.
 * 
 * <p>Java class for CreditDefaultSwapOption complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CreditDefaultSwapOption">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.fpml.org/2009/FpML-4-7}OptionBaseExtended">
 *       &lt;sequence>
 *         &lt;element name="strike" type="{http://www.fpml.org/2009/FpML-4-7}CreditOptionStrike"/>
 *         &lt;element ref="{http://www.fpml.org/2009/FpML-4-7}creditDefaultSwap"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CreditDefaultSwapOption", propOrder = {
    "strike",
    "creditDefaultSwap"
})
public class CreditDefaultSwapOption
    extends OptionBaseExtended
{

    @XmlElement(required = true)
    protected CreditOptionStrike strike;
    @XmlElement(required = true)
    protected CreditDefaultSwap creditDefaultSwap;

    /**
     * Gets the value of the strike property.
     * 
     * @return
     *     possible object is
     *     {@link CreditOptionStrike }
     *     
     */
    public CreditOptionStrike getStrike() {
        return strike;
    }

    /**
     * Sets the value of the strike property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreditOptionStrike }
     *     
     */
    public void setStrike(CreditOptionStrike value) {
        this.strike = value;
    }

    /**
     * Gets the value of the creditDefaultSwap property.
     * 
     * @return
     *     possible object is
     *     {@link CreditDefaultSwap }
     *     
     */
    public CreditDefaultSwap getCreditDefaultSwap() {
        return creditDefaultSwap;
    }

    /**
     * Sets the value of the creditDefaultSwap property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreditDefaultSwap }
     *     
     */
    public void setCreditDefaultSwap(CreditDefaultSwap value) {
        this.creditDefaultSwap = value;
    }

}
