//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.16 at 08:55:11 PM EDT 
//


package org.fpml._2009.fpml_4_7;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * The type defining a denominator term of the formula. Its value is (sum of weighted partials) ^ power.
 * 
 * <p>Java class for DenominatorTerm complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DenominatorTerm">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="weightedPartial" type="{http://www.fpml.org/2009/FpML-4-7}WeightedPartialDerivative"/>
 *         &lt;element name="power" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DenominatorTerm", propOrder = {
    "weightedPartial",
    "power"
})
public class DenominatorTerm {

    @XmlElement(required = true)
    protected WeightedPartialDerivative weightedPartial;
    @XmlElement(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger power;

    /**
     * Gets the value of the weightedPartial property.
     * 
     * @return
     *     possible object is
     *     {@link WeightedPartialDerivative }
     *     
     */
    public WeightedPartialDerivative getWeightedPartial() {
        return weightedPartial;
    }

    /**
     * Sets the value of the weightedPartial property.
     * 
     * @param value
     *     allowed object is
     *     {@link WeightedPartialDerivative }
     *     
     */
    public void setWeightedPartial(WeightedPartialDerivative value) {
        this.weightedPartial = value;
    }

    /**
     * Gets the value of the power property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPower() {
        return power;
    }

    /**
     * Sets the value of the power property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPower(BigInteger value) {
        this.power = value;
    }

}
