//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.16 at 08:53:09 PM EDT 
//


package org.fpml._2009.fpml_4_7;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * This type has been DEPRECATED. It will be removed in the next FpML major version. A type describing the equity leg of a return type swap.
 * 
 * <p>Java class for DeprecatedEquityLeg complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DeprecatedEquityLeg">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.fpml.org/2009/FpML-4-7}ReturnSwapLeg">
 *       &lt;sequence>
 *         &lt;element name="effectiveDate" type="{http://www.fpml.org/2009/FpML-4-7}AdjustableOrRelativeDate"/>
 *         &lt;element name="terminationDate" type="{http://www.fpml.org/2009/FpML-4-7}AdjustableOrRelativeDate"/>
 *         &lt;element name="underlyer" type="{http://www.fpml.org/2009/FpML-4-7}Underlyer"/>
 *         &lt;element name="valuation" type="{http://www.fpml.org/2009/FpML-4-7}DeprecatedEquityLegValuation"/>
 *         &lt;element name="notional" type="{http://www.fpml.org/2009/FpML-4-7}ReturnSwapNotional"/>
 *         &lt;element name="equityAmount" type="{http://www.fpml.org/2009/FpML-4-7}ReturnSwapAmount"/>
 *         &lt;element name="return" type="{http://www.fpml.org/2009/FpML-4-7}Return"/>
 *         &lt;element name="notionalAdjustments" type="{http://www.fpml.org/2009/FpML-4-7}NotionalAdjustmentEnum"/>
 *         &lt;element name="fxFeature" type="{http://www.fpml.org/2009/FpML-4-7}FxFeature" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DeprecatedEquityLeg", propOrder = {
    "effectiveDate",
    "terminationDate",
    "underlyer",
    "valuation",
    "notional",
    "equityAmount",
    "_return",
    "notionalAdjustments",
    "fxFeature"
})
public class DeprecatedEquityLeg
    extends ReturnSwapLeg
{

    @XmlElement(required = true)
    protected AdjustableOrRelativeDate effectiveDate;
    @XmlElement(required = true)
    protected AdjustableOrRelativeDate terminationDate;
    @XmlElement(required = true)
    protected Underlyer underlyer;
    @XmlElement(required = true)
    protected DeprecatedEquityLegValuation valuation;
    @XmlElement(required = true)
    protected ReturnSwapNotional notional;
    @XmlElement(required = true)
    protected ReturnSwapAmount equityAmount;
    @XmlElement(name = "return", required = true)
    protected Return _return;
    @XmlElement(required = true)
    protected NotionalAdjustmentEnum notionalAdjustments;
    protected FxFeature fxFeature;

    /**
     * Gets the value of the effectiveDate property.
     * 
     * @return
     *     possible object is
     *     {@link AdjustableOrRelativeDate }
     *     
     */
    public AdjustableOrRelativeDate getEffectiveDate() {
        return effectiveDate;
    }

    /**
     * Sets the value of the effectiveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdjustableOrRelativeDate }
     *     
     */
    public void setEffectiveDate(AdjustableOrRelativeDate value) {
        this.effectiveDate = value;
    }

    /**
     * Gets the value of the terminationDate property.
     * 
     * @return
     *     possible object is
     *     {@link AdjustableOrRelativeDate }
     *     
     */
    public AdjustableOrRelativeDate getTerminationDate() {
        return terminationDate;
    }

    /**
     * Sets the value of the terminationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdjustableOrRelativeDate }
     *     
     */
    public void setTerminationDate(AdjustableOrRelativeDate value) {
        this.terminationDate = value;
    }

    /**
     * Gets the value of the underlyer property.
     * 
     * @return
     *     possible object is
     *     {@link Underlyer }
     *     
     */
    public Underlyer getUnderlyer() {
        return underlyer;
    }

    /**
     * Sets the value of the underlyer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Underlyer }
     *     
     */
    public void setUnderlyer(Underlyer value) {
        this.underlyer = value;
    }

    /**
     * Gets the value of the valuation property.
     * 
     * @return
     *     possible object is
     *     {@link DeprecatedEquityLegValuation }
     *     
     */
    public DeprecatedEquityLegValuation getValuation() {
        return valuation;
    }

    /**
     * Sets the value of the valuation property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeprecatedEquityLegValuation }
     *     
     */
    public void setValuation(DeprecatedEquityLegValuation value) {
        this.valuation = value;
    }

    /**
     * Gets the value of the notional property.
     * 
     * @return
     *     possible object is
     *     {@link ReturnSwapNotional }
     *     
     */
    public ReturnSwapNotional getNotional() {
        return notional;
    }

    /**
     * Sets the value of the notional property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReturnSwapNotional }
     *     
     */
    public void setNotional(ReturnSwapNotional value) {
        this.notional = value;
    }

    /**
     * Gets the value of the equityAmount property.
     * 
     * @return
     *     possible object is
     *     {@link ReturnSwapAmount }
     *     
     */
    public ReturnSwapAmount getEquityAmount() {
        return equityAmount;
    }

    /**
     * Sets the value of the equityAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReturnSwapAmount }
     *     
     */
    public void setEquityAmount(ReturnSwapAmount value) {
        this.equityAmount = value;
    }

    /**
     * Gets the value of the return property.
     * 
     * @return
     *     possible object is
     *     {@link Return }
     *     
     */
    public Return getReturn() {
        return _return;
    }

    /**
     * Sets the value of the return property.
     * 
     * @param value
     *     allowed object is
     *     {@link Return }
     *     
     */
    public void setReturn(Return value) {
        this._return = value;
    }

    /**
     * Gets the value of the notionalAdjustments property.
     * 
     * @return
     *     possible object is
     *     {@link NotionalAdjustmentEnum }
     *     
     */
    public NotionalAdjustmentEnum getNotionalAdjustments() {
        return notionalAdjustments;
    }

    /**
     * Sets the value of the notionalAdjustments property.
     * 
     * @param value
     *     allowed object is
     *     {@link NotionalAdjustmentEnum }
     *     
     */
    public void setNotionalAdjustments(NotionalAdjustmentEnum value) {
        this.notionalAdjustments = value;
    }

    /**
     * Gets the value of the fxFeature property.
     * 
     * @return
     *     possible object is
     *     {@link FxFeature }
     *     
     */
    public FxFeature getFxFeature() {
        return fxFeature;
    }

    /**
     * Sets the value of the fxFeature property.
     * 
     * @param value
     *     allowed object is
     *     {@link FxFeature }
     *     
     */
    public void setFxFeature(FxFeature value) {
        this.fxFeature = value;
    }

}
