//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.16 at 08:54:46 PM EDT 
//


package org.fpml._2009.fpml_4_7;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A time bounded dividend period, with an expected dividend for each period.
 * 
 * <p>Java class for DividendPeriodDividend complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DividendPeriodDividend">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.fpml.org/2009/FpML-4-7}DividendPeriod">
 *       &lt;sequence>
 *         &lt;element name="dividend" type="{http://www.fpml.org/2009/FpML-4-7}Money"/>
 *         &lt;element name="multiplier" type="{http://www.fpml.org/2009/FpML-4-7}PositiveDecimal"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DividendPeriodDividend", propOrder = {
    "dividend",
    "multiplier"
})
public class DividendPeriodDividend
    extends DividendPeriod
{

    @XmlElement(required = true)
    protected Money dividend;
    @XmlElement(required = true)
    protected BigDecimal multiplier;

    /**
     * Gets the value of the dividend property.
     * 
     * @return
     *     possible object is
     *     {@link Money }
     *     
     */
    public Money getDividend() {
        return dividend;
    }

    /**
     * Sets the value of the dividend property.
     * 
     * @param value
     *     allowed object is
     *     {@link Money }
     *     
     */
    public void setDividend(Money value) {
        this.dividend = value;
    }

    /**
     * Gets the value of the multiplier property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMultiplier() {
        return multiplier;
    }

    /**
     * Sets the value of the multiplier property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMultiplier(BigDecimal value) {
        this.multiplier = value;
    }

}
