//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.16 at 08:54:58 PM EDT 
//


package org.fpml._2009.fpml_4_7;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Physically settled leg of a physically settled electricity transaction.
 * 
 * <p>Java class for ElectricityPhysicalLeg complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ElectricityPhysicalLeg">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.fpml.org/2009/FpML-4-7}PhysicalLeg">
 *       &lt;sequence>
 *         &lt;element name="deliveryPeriods" type="{http://www.fpml.org/2009/FpML-4-7}CommodityDeliveryPeriods"/>
 *         &lt;element name="settlementPeriods" type="{http://www.fpml.org/2009/FpML-4-7}SettlementPeriods" maxOccurs="unbounded"/>
 *         &lt;element name="settlementPeriodsSchedule" type="{http://www.fpml.org/2009/FpML-4-7}SettlementPeriodsSchedule" minOccurs="0"/>
 *         &lt;element name="electricity" type="{http://www.fpml.org/2009/FpML-4-7}ElectricityProduct"/>
 *         &lt;element name="deliveryConditions" type="{http://www.fpml.org/2009/FpML-4-7}ElectricityDelivery"/>
 *         &lt;element name="deliveryQuantity" type="{http://www.fpml.org/2009/FpML-4-7}ElectricityPhysicalQuantity"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ElectricityPhysicalLeg", propOrder = {
    "deliveryPeriods",
    "settlementPeriods",
    "settlementPeriodsSchedule",
    "electricity",
    "deliveryConditions",
    "deliveryQuantity"
})
public class ElectricityPhysicalLeg
    extends PhysicalLeg
{

    @XmlElement(required = true)
    protected CommodityDeliveryPeriods deliveryPeriods;
    @XmlElement(required = true)
    protected List<SettlementPeriods> settlementPeriods;
    protected SettlementPeriodsSchedule settlementPeriodsSchedule;
    @XmlElement(required = true)
    protected ElectricityProduct electricity;
    @XmlElement(required = true)
    protected ElectricityDelivery deliveryConditions;
    @XmlElement(required = true)
    protected ElectricityPhysicalQuantity deliveryQuantity;

    /**
     * Gets the value of the deliveryPeriods property.
     * 
     * @return
     *     possible object is
     *     {@link CommodityDeliveryPeriods }
     *     
     */
    public CommodityDeliveryPeriods getDeliveryPeriods() {
        return deliveryPeriods;
    }

    /**
     * Sets the value of the deliveryPeriods property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommodityDeliveryPeriods }
     *     
     */
    public void setDeliveryPeriods(CommodityDeliveryPeriods value) {
        this.deliveryPeriods = value;
    }

    /**
     * Gets the value of the settlementPeriods property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the settlementPeriods property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSettlementPeriods().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SettlementPeriods }
     * 
     * 
     */
    public List<SettlementPeriods> getSettlementPeriods() {
        if (settlementPeriods == null) {
            settlementPeriods = new ArrayList<SettlementPeriods>();
        }
        return this.settlementPeriods;
    }

    /**
     * Gets the value of the settlementPeriodsSchedule property.
     * 
     * @return
     *     possible object is
     *     {@link SettlementPeriodsSchedule }
     *     
     */
    public SettlementPeriodsSchedule getSettlementPeriodsSchedule() {
        return settlementPeriodsSchedule;
    }

    /**
     * Sets the value of the settlementPeriodsSchedule property.
     * 
     * @param value
     *     allowed object is
     *     {@link SettlementPeriodsSchedule }
     *     
     */
    public void setSettlementPeriodsSchedule(SettlementPeriodsSchedule value) {
        this.settlementPeriodsSchedule = value;
    }

    /**
     * Gets the value of the electricity property.
     * 
     * @return
     *     possible object is
     *     {@link ElectricityProduct }
     *     
     */
    public ElectricityProduct getElectricity() {
        return electricity;
    }

    /**
     * Sets the value of the electricity property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElectricityProduct }
     *     
     */
    public void setElectricity(ElectricityProduct value) {
        this.electricity = value;
    }

    /**
     * Gets the value of the deliveryConditions property.
     * 
     * @return
     *     possible object is
     *     {@link ElectricityDelivery }
     *     
     */
    public ElectricityDelivery getDeliveryConditions() {
        return deliveryConditions;
    }

    /**
     * Sets the value of the deliveryConditions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElectricityDelivery }
     *     
     */
    public void setDeliveryConditions(ElectricityDelivery value) {
        this.deliveryConditions = value;
    }

    /**
     * Gets the value of the deliveryQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link ElectricityPhysicalQuantity }
     *     
     */
    public ElectricityPhysicalQuantity getDeliveryQuantity() {
        return deliveryQuantity;
    }

    /**
     * Sets the value of the deliveryQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElectricityPhysicalQuantity }
     *     
     */
    public void setDeliveryQuantity(ElectricityPhysicalQuantity value) {
        this.deliveryQuantity = value;
    }

}
