//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.16 at 08:54:24 PM EDT 
//


package org.fpml._2009.fpml_4_7;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * type for defining the common features of equity derivatives.
 * 
 * <p>Java class for EquityDerivativeLongFormBase complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EquityDerivativeLongFormBase">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.fpml.org/2009/FpML-4-7}EquityDerivativeBase">
 *       &lt;sequence>
 *         &lt;element name="dividendConditions" type="{http://www.fpml.org/2009/FpML-4-7}DividendConditions" minOccurs="0"/>
 *         &lt;element name="methodOfAdjustment" type="{http://www.fpml.org/2009/FpML-4-7}MethodOfAdjustmentEnum"/>
 *         &lt;element name="extraordinaryEvents" type="{http://www.fpml.org/2009/FpML-4-7}ExtraordinaryEvents"/>
 *         &lt;element name="equityFeatures" type="{http://www.fpml.org/2009/FpML-4-7}OptionFeatures" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EquityDerivativeLongFormBase", propOrder = {
    "dividendConditions",
    "methodOfAdjustment",
    "extraordinaryEvents",
    "equityFeatures"
})
@XmlSeeAlso({
    EquityForward.class,
    EquityOption.class
})
public abstract class EquityDerivativeLongFormBase
    extends EquityDerivativeBase
{

    protected DividendConditions dividendConditions;
    @XmlElement(required = true)
    protected MethodOfAdjustmentEnum methodOfAdjustment;
    @XmlElement(required = true)
    protected ExtraordinaryEvents extraordinaryEvents;
    protected OptionFeatures equityFeatures;

    /**
     * Gets the value of the dividendConditions property.
     * 
     * @return
     *     possible object is
     *     {@link DividendConditions }
     *     
     */
    public DividendConditions getDividendConditions() {
        return dividendConditions;
    }

    /**
     * Sets the value of the dividendConditions property.
     * 
     * @param value
     *     allowed object is
     *     {@link DividendConditions }
     *     
     */
    public void setDividendConditions(DividendConditions value) {
        this.dividendConditions = value;
    }

    /**
     * Gets the value of the methodOfAdjustment property.
     * 
     * @return
     *     possible object is
     *     {@link MethodOfAdjustmentEnum }
     *     
     */
    public MethodOfAdjustmentEnum getMethodOfAdjustment() {
        return methodOfAdjustment;
    }

    /**
     * Sets the value of the methodOfAdjustment property.
     * 
     * @param value
     *     allowed object is
     *     {@link MethodOfAdjustmentEnum }
     *     
     */
    public void setMethodOfAdjustment(MethodOfAdjustmentEnum value) {
        this.methodOfAdjustment = value;
    }

    /**
     * Gets the value of the extraordinaryEvents property.
     * 
     * @return
     *     possible object is
     *     {@link ExtraordinaryEvents }
     *     
     */
    public ExtraordinaryEvents getExtraordinaryEvents() {
        return extraordinaryEvents;
    }

    /**
     * Sets the value of the extraordinaryEvents property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtraordinaryEvents }
     *     
     */
    public void setExtraordinaryEvents(ExtraordinaryEvents value) {
        this.extraordinaryEvents = value;
    }

    /**
     * Gets the value of the equityFeatures property.
     * 
     * @return
     *     possible object is
     *     {@link OptionFeatures }
     *     
     */
    public OptionFeatures getEquityFeatures() {
        return equityFeatures;
    }

    /**
     * Sets the value of the equityFeatures property.
     * 
     * @param value
     *     allowed object is
     *     {@link OptionFeatures }
     *     
     */
    public void setEquityFeatures(OptionFeatures value) {
        this.equityFeatures = value;
    }

}
