//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.16 at 08:54:46 PM EDT 
//


package org.fpml._2009.fpml_4_7;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Where the underlying is shares, defines market events affecting the issuer of those shares that may require the terms of the transaction to be adjusted.
 * 
 * <p>Java class for ExtraordinaryEvents complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExtraordinaryEvents">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="mergerEvents" type="{http://www.fpml.org/2009/FpML-4-7}EquityCorporateEvents" minOccurs="0"/>
 *         &lt;element name="tenderOffer" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="tenderOfferEvents" type="{http://www.fpml.org/2009/FpML-4-7}EquityCorporateEvents" minOccurs="0"/>
 *         &lt;element name="compositionOfCombinedConsideration" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="indexAdjustmentEvents" type="{http://www.fpml.org/2009/FpML-4-7}IndexAdjustmentEvents" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element name="additionalDisruptionEvents" type="{http://www.fpml.org/2009/FpML-4-7}AdditionalDisruptionEvents"/>
 *           &lt;element name="failureToDeliver" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;/choice>
 *         &lt;element name="representations" type="{http://www.fpml.org/2009/FpML-4-7}Representations" minOccurs="0"/>
 *         &lt;element name="nationalisationOrInsolvency" type="{http://www.fpml.org/2009/FpML-4-7}NationalisationOrInsolvencyOrDelistingEventEnum" minOccurs="0"/>
 *         &lt;element name="delisting" type="{http://www.fpml.org/2009/FpML-4-7}NationalisationOrInsolvencyOrDelistingEventEnum" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExtraordinaryEvents", propOrder = {
    "mergerEvents",
    "tenderOffer",
    "tenderOfferEvents",
    "compositionOfCombinedConsideration",
    "indexAdjustmentEvents",
    "additionalDisruptionEvents",
    "failureToDeliver",
    "representations",
    "nationalisationOrInsolvency",
    "delisting"
})
public class ExtraordinaryEvents {

    protected EquityCorporateEvents mergerEvents;
    protected Boolean tenderOffer;
    protected EquityCorporateEvents tenderOfferEvents;
    protected Boolean compositionOfCombinedConsideration;
    protected IndexAdjustmentEvents indexAdjustmentEvents;
    protected AdditionalDisruptionEvents additionalDisruptionEvents;
    protected Boolean failureToDeliver;
    protected Representations representations;
    protected NationalisationOrInsolvencyOrDelistingEventEnum nationalisationOrInsolvency;
    protected NationalisationOrInsolvencyOrDelistingEventEnum delisting;

    /**
     * Gets the value of the mergerEvents property.
     * 
     * @return
     *     possible object is
     *     {@link EquityCorporateEvents }
     *     
     */
    public EquityCorporateEvents getMergerEvents() {
        return mergerEvents;
    }

    /**
     * Sets the value of the mergerEvents property.
     * 
     * @param value
     *     allowed object is
     *     {@link EquityCorporateEvents }
     *     
     */
    public void setMergerEvents(EquityCorporateEvents value) {
        this.mergerEvents = value;
    }

    /**
     * Gets the value of the tenderOffer property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTenderOffer() {
        return tenderOffer;
    }

    /**
     * Sets the value of the tenderOffer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTenderOffer(Boolean value) {
        this.tenderOffer = value;
    }

    /**
     * Gets the value of the tenderOfferEvents property.
     * 
     * @return
     *     possible object is
     *     {@link EquityCorporateEvents }
     *     
     */
    public EquityCorporateEvents getTenderOfferEvents() {
        return tenderOfferEvents;
    }

    /**
     * Sets the value of the tenderOfferEvents property.
     * 
     * @param value
     *     allowed object is
     *     {@link EquityCorporateEvents }
     *     
     */
    public void setTenderOfferEvents(EquityCorporateEvents value) {
        this.tenderOfferEvents = value;
    }

    /**
     * Gets the value of the compositionOfCombinedConsideration property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCompositionOfCombinedConsideration() {
        return compositionOfCombinedConsideration;
    }

    /**
     * Sets the value of the compositionOfCombinedConsideration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCompositionOfCombinedConsideration(Boolean value) {
        this.compositionOfCombinedConsideration = value;
    }

    /**
     * Gets the value of the indexAdjustmentEvents property.
     * 
     * @return
     *     possible object is
     *     {@link IndexAdjustmentEvents }
     *     
     */
    public IndexAdjustmentEvents getIndexAdjustmentEvents() {
        return indexAdjustmentEvents;
    }

    /**
     * Sets the value of the indexAdjustmentEvents property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndexAdjustmentEvents }
     *     
     */
    public void setIndexAdjustmentEvents(IndexAdjustmentEvents value) {
        this.indexAdjustmentEvents = value;
    }

    /**
     * Gets the value of the additionalDisruptionEvents property.
     * 
     * @return
     *     possible object is
     *     {@link AdditionalDisruptionEvents }
     *     
     */
    public AdditionalDisruptionEvents getAdditionalDisruptionEvents() {
        return additionalDisruptionEvents;
    }

    /**
     * Sets the value of the additionalDisruptionEvents property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdditionalDisruptionEvents }
     *     
     */
    public void setAdditionalDisruptionEvents(AdditionalDisruptionEvents value) {
        this.additionalDisruptionEvents = value;
    }

    /**
     * Gets the value of the failureToDeliver property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFailureToDeliver() {
        return failureToDeliver;
    }

    /**
     * Sets the value of the failureToDeliver property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFailureToDeliver(Boolean value) {
        this.failureToDeliver = value;
    }

    /**
     * Gets the value of the representations property.
     * 
     * @return
     *     possible object is
     *     {@link Representations }
     *     
     */
    public Representations getRepresentations() {
        return representations;
    }

    /**
     * Sets the value of the representations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Representations }
     *     
     */
    public void setRepresentations(Representations value) {
        this.representations = value;
    }

    /**
     * Gets the value of the nationalisationOrInsolvency property.
     * 
     * @return
     *     possible object is
     *     {@link NationalisationOrInsolvencyOrDelistingEventEnum }
     *     
     */
    public NationalisationOrInsolvencyOrDelistingEventEnum getNationalisationOrInsolvency() {
        return nationalisationOrInsolvency;
    }

    /**
     * Sets the value of the nationalisationOrInsolvency property.
     * 
     * @param value
     *     allowed object is
     *     {@link NationalisationOrInsolvencyOrDelistingEventEnum }
     *     
     */
    public void setNationalisationOrInsolvency(NationalisationOrInsolvencyOrDelistingEventEnum value) {
        this.nationalisationOrInsolvency = value;
    }

    /**
     * Gets the value of the delisting property.
     * 
     * @return
     *     possible object is
     *     {@link NationalisationOrInsolvencyOrDelistingEventEnum }
     *     
     */
    public NationalisationOrInsolvencyOrDelistingEventEnum getDelisting() {
        return delisting;
    }

    /**
     * Sets the value of the delisting property.
     * 
     * @param value
     *     allowed object is
     *     {@link NationalisationOrInsolvencyOrDelistingEventEnum }
     *     
     */
    public void setDelisting(NationalisationOrInsolvencyOrDelistingEventEnum value) {
        this.delisting = value;
    }

}
