//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.16 at 08:55:11 PM EDT 
//


package org.fpml._2009.fpml_4_7;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FloatingAmountProvisions complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FloatingAmountProvisions">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="WACCapInterestProvision" type="{http://www.fpml.org/2009/FpML-4-7}Empty" minOccurs="0"/>
 *         &lt;element name="stepUpProvision" type="{http://www.fpml.org/2009/FpML-4-7}Empty" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FloatingAmountProvisions", propOrder = {
    "wacCapInterestProvision",
    "stepUpProvision"
})
public class FloatingAmountProvisions {

    @XmlElement(name = "WACCapInterestProvision")
    protected Empty wacCapInterestProvision;
    protected Empty stepUpProvision;

    /**
     * Gets the value of the wacCapInterestProvision property.
     * 
     * @return
     *     possible object is
     *     {@link Empty }
     *     
     */
    public Empty getWACCapInterestProvision() {
        return wacCapInterestProvision;
    }

    /**
     * Sets the value of the wacCapInterestProvision property.
     * 
     * @param value
     *     allowed object is
     *     {@link Empty }
     *     
     */
    public void setWACCapInterestProvision(Empty value) {
        this.wacCapInterestProvision = value;
    }

    /**
     * Gets the value of the stepUpProvision property.
     * 
     * @return
     *     possible object is
     *     {@link Empty }
     *     
     */
    public Empty getStepUpProvision() {
        return stepUpProvision;
    }

    /**
     * Sets the value of the stepUpProvision property.
     * 
     * @param value
     *     allowed object is
     *     {@link Empty }
     *     
     */
    public void setStepUpProvision(Empty value) {
        this.stepUpProvision = value;
    }

}
