//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.16 at 08:55:11 PM EDT 
//


package org.fpml._2009.fpml_4_7;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A type defining a term of the formula. Its value is the product of the its coefficient and the referenced partial derivatives.
 * 
 * <p>Java class for FormulaTerm complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FormulaTerm">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="coefficient" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="partialDerivativeReference" type="{http://www.fpml.org/2009/FpML-4-7}PricingParameterDerivativeReference" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FormulaTerm", propOrder = {
    "coefficient",
    "partialDerivativeReference"
})
public class FormulaTerm {

    @XmlElement(required = true)
    protected BigDecimal coefficient;
    @XmlElement(required = true)
    protected List<PricingParameterDerivativeReference> partialDerivativeReference;

    /**
     * Gets the value of the coefficient property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCoefficient() {
        return coefficient;
    }

    /**
     * Sets the value of the coefficient property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCoefficient(BigDecimal value) {
        this.coefficient = value;
    }

    /**
     * Gets the value of the partialDerivativeReference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the partialDerivativeReference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPartialDerivativeReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PricingParameterDerivativeReference }
     * 
     * 
     */
    public List<PricingParameterDerivativeReference> getPartialDerivativeReference() {
        if (partialDerivativeReference == null) {
            partialDerivativeReference = new ArrayList<PricingParameterDerivativeReference>();
        }
        return this.partialDerivativeReference;
    }

}
