//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.16 at 08:54:58 PM EDT 
//


package org.fpml._2009.fpml_4_7;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * An observation period that is offset from a Calculation Period.
 * 
 * <p>Java class for Lag complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Lag">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="lagDuration" type="{http://www.fpml.org/2009/FpML-4-7}Period"/>
 *         &lt;element name="firstObservationDateOffset" type="{http://www.fpml.org/2009/FpML-4-7}Period" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Lag", propOrder = {
    "lagDuration",
    "firstObservationDateOffset"
})
public class Lag {

    @XmlElement(required = true)
    protected Period lagDuration;
    protected Period firstObservationDateOffset;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Gets the value of the lagDuration property.
     * 
     * @return
     *     possible object is
     *     {@link Period }
     *     
     */
    public Period getLagDuration() {
        return lagDuration;
    }

    /**
     * Sets the value of the lagDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Period }
     *     
     */
    public void setLagDuration(Period value) {
        this.lagDuration = value;
    }

    /**
     * Gets the value of the firstObservationDateOffset property.
     * 
     * @return
     *     possible object is
     *     {@link Period }
     *     
     */
    public Period getFirstObservationDateOffset() {
        return firstObservationDateOffset;
    }

    /**
     * Sets the value of the firstObservationDateOffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link Period }
     *     
     */
    public void setFirstObservationDateOffset(Period value) {
        this.firstObservationDateOffset = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
