//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.16 at 08:54:16 PM EDT 
//


package org.fpml._2009.fpml_4_7;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * A type to define an early termination provision for which exercise is mandatory.
 * 
 * <p>Java class for MandatoryEarlyTermination complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MandatoryEarlyTermination">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="mandatoryEarlyTerminationDate" type="{http://www.fpml.org/2009/FpML-4-7}AdjustableDate"/>
 *         &lt;element name="calculationAgent" type="{http://www.fpml.org/2009/FpML-4-7}CalculationAgent"/>
 *         &lt;element name="cashSettlement" type="{http://www.fpml.org/2009/FpML-4-7}CashSettlement"/>
 *         &lt;element name="mandatoryEarlyTerminationAdjustedDates" type="{http://www.fpml.org/2009/FpML-4-7}MandatoryEarlyTerminationAdjustedDates" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MandatoryEarlyTermination", propOrder = {
    "mandatoryEarlyTerminationDate",
    "calculationAgent",
    "cashSettlement",
    "mandatoryEarlyTerminationAdjustedDates"
})
public class MandatoryEarlyTermination {

    @XmlElement(required = true)
    protected AdjustableDate mandatoryEarlyTerminationDate;
    @XmlElement(required = true)
    protected CalculationAgent calculationAgent;
    @XmlElement(required = true)
    protected CashSettlement cashSettlement;
    protected MandatoryEarlyTerminationAdjustedDates mandatoryEarlyTerminationAdjustedDates;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Gets the value of the mandatoryEarlyTerminationDate property.
     * 
     * @return
     *     possible object is
     *     {@link AdjustableDate }
     *     
     */
    public AdjustableDate getMandatoryEarlyTerminationDate() {
        return mandatoryEarlyTerminationDate;
    }

    /**
     * Sets the value of the mandatoryEarlyTerminationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdjustableDate }
     *     
     */
    public void setMandatoryEarlyTerminationDate(AdjustableDate value) {
        this.mandatoryEarlyTerminationDate = value;
    }

    /**
     * Gets the value of the calculationAgent property.
     * 
     * @return
     *     possible object is
     *     {@link CalculationAgent }
     *     
     */
    public CalculationAgent getCalculationAgent() {
        return calculationAgent;
    }

    /**
     * Sets the value of the calculationAgent property.
     * 
     * @param value
     *     allowed object is
     *     {@link CalculationAgent }
     *     
     */
    public void setCalculationAgent(CalculationAgent value) {
        this.calculationAgent = value;
    }

    /**
     * Gets the value of the cashSettlement property.
     * 
     * @return
     *     possible object is
     *     {@link CashSettlement }
     *     
     */
    public CashSettlement getCashSettlement() {
        return cashSettlement;
    }

    /**
     * Sets the value of the cashSettlement property.
     * 
     * @param value
     *     allowed object is
     *     {@link CashSettlement }
     *     
     */
    public void setCashSettlement(CashSettlement value) {
        this.cashSettlement = value;
    }

    /**
     * Gets the value of the mandatoryEarlyTerminationAdjustedDates property.
     * 
     * @return
     *     possible object is
     *     {@link MandatoryEarlyTerminationAdjustedDates }
     *     
     */
    public MandatoryEarlyTerminationAdjustedDates getMandatoryEarlyTerminationAdjustedDates() {
        return mandatoryEarlyTerminationAdjustedDates;
    }

    /**
     * Sets the value of the mandatoryEarlyTerminationAdjustedDates property.
     * 
     * @param value
     *     allowed object is
     *     {@link MandatoryEarlyTerminationAdjustedDates }
     *     
     */
    public void setMandatoryEarlyTerminationAdjustedDates(MandatoryEarlyTerminationAdjustedDates value) {
        this.mandatoryEarlyTerminationAdjustedDates = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
