//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.16 at 08:54:11 PM EDT 
//


package org.fpml._2009.fpml_4_7;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Information about single maturing loan contract.
 * 
 * <p>Java class for MaturingLoanContract complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MaturingLoanContract">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="loanContractSummary" type="{http://www.fpml.org/2009/FpML-4-7}LoanContractSummary"/>
 *         &lt;group ref="{http://www.fpml.org/2009/FpML-4-7}InterestPaymentDetails.model" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MaturingLoanContract", propOrder = {
    "loanContractSummary",
    "interestPayment",
    "interestAccrualSchedule"
})
public class MaturingLoanContract {

    @XmlElement(required = true)
    protected LoanContractSummary loanContractSummary;
    protected InterestPayment interestPayment;
    protected InterestAccrualSchedule interestAccrualSchedule;

    /**
     * Gets the value of the loanContractSummary property.
     * 
     * @return
     *     possible object is
     *     {@link LoanContractSummary }
     *     
     */
    public LoanContractSummary getLoanContractSummary() {
        return loanContractSummary;
    }

    /**
     * Sets the value of the loanContractSummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link LoanContractSummary }
     *     
     */
    public void setLoanContractSummary(LoanContractSummary value) {
        this.loanContractSummary = value;
    }

    /**
     * Gets the value of the interestPayment property.
     * 
     * @return
     *     possible object is
     *     {@link InterestPayment }
     *     
     */
    public InterestPayment getInterestPayment() {
        return interestPayment;
    }

    /**
     * Sets the value of the interestPayment property.
     * 
     * @param value
     *     allowed object is
     *     {@link InterestPayment }
     *     
     */
    public void setInterestPayment(InterestPayment value) {
        this.interestPayment = value;
    }

    /**
     * Gets the value of the interestAccrualSchedule property.
     * 
     * @return
     *     possible object is
     *     {@link InterestAccrualSchedule }
     *     
     */
    public InterestAccrualSchedule getInterestAccrualSchedule() {
        return interestAccrualSchedule;
    }

    /**
     * Sets the value of the interestAccrualSchedule property.
     * 
     * @param value
     *     allowed object is
     *     {@link InterestAccrualSchedule }
     *     
     */
    public void setInterestAccrualSchedule(InterestAccrualSchedule value) {
        this.interestAccrualSchedule = value;
    }

}
