//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.16 at 08:55:21 PM EDT 
//


package org.fpml._2009.fpml_4_7;

import java.math.BigDecimal;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.fpml._2009.fpml_4_7 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Exercise_QNAME = new QName("http://www.fpml.org/2009/FpML-4-7", "exercise");
    private final static QName _AmericanExercise_QNAME = new QName("http://www.fpml.org/2009/FpML-4-7", "americanExercise");
    private final static QName _Event_QNAME = new QName("http://www.fpml.org/2009/FpML-4-7", "event");
    private final static QName _BermudaExercise_QNAME = new QName("http://www.fpml.org/2009/FpML-4-7", "bermudaExercise");
    private final static QName _EuropeanExercise_QNAME = new QName("http://www.fpml.org/2009/FpML-4-7", "europeanExercise");
    private final static QName _Strategy_QNAME = new QName("http://www.fpml.org/2009/FpML-4-7", "strategy");
    private final static QName _Product_QNAME = new QName("http://www.fpml.org/2009/FpML-4-7", "product");
    private final static QName _NovationRemainingParty_QNAME = new QName("http://www.fpml.org/2009/FpML-4-7", "remainingParty");
    private final static QName _NovationFirstPeriodStartDate_QNAME = new QName("http://www.fpml.org/2009/FpML-4-7", "firstPeriodStartDate");
    private final static QName _NovationTransferee_QNAME = new QName("http://www.fpml.org/2009/FpML-4-7", "transferee");
    private final static QName _NovationOtherRemainingParty_QNAME = new QName("http://www.fpml.org/2009/FpML-4-7", "otherRemainingParty");
    private final static QName _NovationNewTransactionReference_QNAME = new QName("http://www.fpml.org/2009/FpML-4-7", "newTransactionReference");
    private final static QName _NovationOldTransactionReference_QNAME = new QName("http://www.fpml.org/2009/FpML-4-7", "oldTransactionReference");
    private final static QName _NovationNovationDate_QNAME = new QName("http://www.fpml.org/2009/FpML-4-7", "novationDate");
    private final static QName _NovationPayment_QNAME = new QName("http://www.fpml.org/2009/FpML-4-7", "payment");
    private final static QName _NovationNovationTradeDate_QNAME = new QName("http://www.fpml.org/2009/FpML-4-7", "novationTradeDate");
    private final static QName _NovationOldTransaction_QNAME = new QName("http://www.fpml.org/2009/FpML-4-7", "oldTransaction");
    private final static QName _NovationNewTransaction_QNAME = new QName("http://www.fpml.org/2009/FpML-4-7", "newTransaction");
    private final static QName _NovationNonReliance_QNAME = new QName("http://www.fpml.org/2009/FpML-4-7", "nonReliance");
    private final static QName _NovationContractualSupplement_QNAME = new QName("http://www.fpml.org/2009/FpML-4-7", "contractualSupplement");
    private final static QName _NovationTransferor_QNAME = new QName("http://www.fpml.org/2009/FpML-4-7", "transferor");
    private final static QName _NovationNovatedNumberOfOptions_QNAME = new QName("http://www.fpml.org/2009/FpML-4-7", "novatedNumberOfOptions");
    private final static QName _NovationRemainingTrade_QNAME = new QName("http://www.fpml.org/2009/FpML-4-7", "remainingTrade");
    private final static QName _NovationContractualTermsSupplement_QNAME = new QName("http://www.fpml.org/2009/FpML-4-7", "contractualTermsSupplement");
    private final static QName _NovationContractualDefinitions_QNAME = new QName("http://www.fpml.org/2009/FpML-4-7", "contractualDefinitions");
    private final static QName _NovationFullFirstCalculationPeriod_QNAME = new QName("http://www.fpml.org/2009/FpML-4-7", "fullFirstCalculationPeriod");
    private final static QName _NovationCreditDerivativesNotices_QNAME = new QName("http://www.fpml.org/2009/FpML-4-7", "creditDerivativesNotices");
    private final static QName _NovationNovatedAmount_QNAME = new QName("http://www.fpml.org/2009/FpML-4-7", "novatedAmount");
    private final static QName _LegalEntityEntityId_QNAME = new QName("http://www.fpml.org/2009/FpML-4-7", "entityId");
    private final static QName _LegalEntityEntityName_QNAME = new QName("http://www.fpml.org/2009/FpML-4-7", "entityName");
    private final static QName _AccountAccountName_QNAME = new QName("http://www.fpml.org/2009/FpML-4-7", "accountName");
    private final static QName _AccountAccountId_QNAME = new QName("http://www.fpml.org/2009/FpML-4-7", "accountId");
    private final static QName _ContractNovationNovationContractDate_QNAME = new QName("http://www.fpml.org/2009/FpML-4-7", "novationContractDate");
    private final static QName _ContractNovationOldContract_QNAME = new QName("http://www.fpml.org/2009/FpML-4-7", "oldContract");
    private final static QName _ContractNovationOldContractReference_QNAME = new QName("http://www.fpml.org/2009/FpML-4-7", "oldContractReference");
    private final static QName _ContractNovationNewContractReference_QNAME = new QName("http://www.fpml.org/2009/FpML-4-7", "newContractReference");
    private final static QName _ContractNovationNovatedNumberOfUnits_QNAME = new QName("http://www.fpml.org/2009/FpML-4-7", "novatedNumberOfUnits");
    private final static QName _ContractNovationNewContract_QNAME = new QName("http://www.fpml.org/2009/FpML-4-7", "newContract");
    private final static QName _PaymentDetailAdjustablePaymentDate_QNAME = new QName("http://www.fpml.org/2009/FpML-4-7", "adjustablePaymentDate");
    private final static QName _PaymentDetailAdjustedPaymentDate_QNAME = new QName("http://www.fpml.org/2009/FpML-4-7", "adjustedPaymentDate");
    private final static QName _PaymentDetailPaymentDate_QNAME = new QName("http://www.fpml.org/2009/FpML-4-7", "paymentDate");
    private final static QName _PaymentDetailPaymentAmount_QNAME = new QName("http://www.fpml.org/2009/FpML-4-7", "paymentAmount");
    private final static QName _PaymentDetailPaymentRule_QNAME = new QName("http://www.fpml.org/2009/FpML-4-7", "paymentRule");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.fpml._2009.fpml_4_7
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TimezoneLocation }
     * 
     */
    public TimezoneLocation createTimezoneLocation() {
        return new TimezoneLocation();
    }

    /**
     * Create an instance of {@link Trader }
     * 
     */
    public Trader createTrader() {
        return new Trader();
    }

    /**
     * Create an instance of {@link QueryPortfolio }
     * 
     */
    public QueryPortfolio createQueryPortfolio() {
        return new QueryPortfolio();
    }

    /**
     * Create an instance of {@link AdjustableDate2 }
     * 
     */
    public AdjustableDate2 createAdjustableDate2() {
        return new AdjustableDate2();
    }

    /**
     * Create an instance of {@link Money }
     * 
     */
    public Money createMoney() {
        return new Money();
    }

    /**
     * Create an instance of {@link CalculationAgent }
     * 
     */
    public CalculationAgent createCalculationAgent() {
        return new CalculationAgent();
    }

    /**
     * Create an instance of {@link ContractInformation }
     * 
     */
    public ContractInformation createContractInformation() {
        return new ContractInformation();
    }

    /**
     * Create an instance of {@link AmountSchedule }
     * 
     */
    public AmountSchedule createAmountSchedule() {
        return new AmountSchedule();
    }

    /**
     * Create an instance of {@link PaymentDetail }
     * 
     */
    public PaymentDetail createPaymentDetail() {
        return new PaymentDetail();
    }

    /**
     * Create an instance of {@link ContractTermination }
     * 
     */
    public ContractTermination createContractTermination() {
        return new ContractTermination();
    }

    /**
     * Create an instance of {@link CreditSupportAgreement }
     * 
     */
    public CreditSupportAgreement createCreditSupportAgreement() {
        return new CreditSupportAgreement();
    }

    /**
     * Create an instance of {@link RateReference }
     * 
     */
    public RateReference createRateReference() {
        return new RateReference();
    }

    /**
     * Create an instance of {@link RequiredIdentifierDate }
     * 
     */
    public RequiredIdentifierDate createRequiredIdentifierDate() {
        return new RequiredIdentifierDate();
    }

    /**
     * Create an instance of {@link Portfolio }
     * 
     */
    public Portfolio createPortfolio() {
        return new Portfolio();
    }

    /**
     * Create an instance of {@link BusinessCentersReference }
     * 
     */
    public BusinessCentersReference createBusinessCentersReference() {
        return new BusinessCentersReference();
    }

    /**
     * Create an instance of {@link ResponseMessageHeader }
     * 
     */
    public ResponseMessageHeader createResponseMessageHeader() {
        return new ResponseMessageHeader();
    }

    /**
     * Create an instance of {@link Contract }
     * 
     */
    public Contract createContract() {
        return new Contract();
    }

    /**
     * Create an instance of {@link RateObservation }
     * 
     */
    public RateObservation createRateObservation() {
        return new RateObservation();
    }

    /**
     * Create an instance of {@link TradeNotFound }
     * 
     */
    public TradeNotFound createTradeNotFound() {
        return new TradeNotFound();
    }

    /**
     * Create an instance of {@link MessageId }
     * 
     */
    public MessageId createMessageId() {
        return new MessageId();
    }

    /**
     * Create an instance of {@link PrincipalExchanges }
     * 
     */
    public PrincipalExchanges createPrincipalExchanges() {
        return new PrincipalExchanges();
    }

    /**
     * Create an instance of {@link RelativeDateSequence }
     * 
     */
    public RelativeDateSequence createRelativeDateSequence() {
        return new RelativeDateSequence();
    }

    /**
     * Create an instance of {@link TradeIdentifier }
     * 
     */
    public TradeIdentifier createTradeIdentifier() {
        return new TradeIdentifier();
    }

    /**
     * Create an instance of {@link RelativeDates }
     * 
     */
    public RelativeDates createRelativeDates() {
        return new RelativeDates();
    }

    /**
     * Create an instance of {@link AccountReference }
     * 
     */
    public AccountReference createAccountReference() {
        return new AccountReference();
    }

    /**
     * Create an instance of {@link PartyTradeInformation }
     * 
     */
    public PartyTradeInformation createPartyTradeInformation() {
        return new PartyTradeInformation();
    }

    /**
     * Create an instance of {@link PositiveSchedule }
     * 
     */
    public PositiveSchedule createPositiveSchedule() {
        return new PositiveSchedule();
    }

    /**
     * Create an instance of {@link DeterminationMethod }
     * 
     */
    public DeterminationMethod createDeterminationMethod() {
        return new DeterminationMethod();
    }

    /**
     * Create an instance of {@link InformationSource }
     * 
     */
    public InformationSource createInformationSource() {
        return new InformationSource();
    }

    /**
     * Create an instance of {@link Country }
     * 
     */
    public Country createCountry() {
        return new Country();
    }

    /**
     * Create an instance of {@link RequestAllocation }
     * 
     */
    public RequestAllocation createRequestAllocation() {
        return new RequestAllocation();
    }

    /**
     * Create an instance of {@link PaymentReference }
     * 
     */
    public PaymentReference createPaymentReference() {
        return new PaymentReference();
    }

    /**
     * Create an instance of {@link PaymentCurrency }
     * 
     */
    public PaymentCurrency createPaymentCurrency() {
        return new PaymentCurrency();
    }

    /**
     * Create an instance of {@link Strike }
     * 
     */
    public Strike createStrike() {
        return new Strike();
    }

    /**
     * Create an instance of {@link Empty }
     * 
     */
    public Empty createEmpty() {
        return new Empty();
    }

    /**
     * Create an instance of {@link Allocations }
     * 
     */
    public Allocations createAllocations() {
        return new Allocations();
    }

    /**
     * Create an instance of {@link CashflowType }
     * 
     */
    public CashflowType createCashflowType() {
        return new CashflowType();
    }

    /**
     * Create an instance of {@link AmountReference }
     * 
     */
    public AmountReference createAmountReference() {
        return new AmountReference();
    }

    /**
     * Create an instance of {@link GoverningLaw }
     * 
     */
    public GoverningLaw createGoverningLaw() {
        return new GoverningLaw();
    }

    /**
     * Create an instance of {@link BusinessCenters }
     * 
     */
    public BusinessCenters createBusinessCenters() {
        return new BusinessCenters();
    }

    /**
     * Create an instance of {@link SpreadScheduleReference }
     * 
     */
    public SpreadScheduleReference createSpreadScheduleReference() {
        return new SpreadScheduleReference();
    }

    /**
     * Create an instance of {@link PartyMessageInformation }
     * 
     */
    public PartyMessageInformation createPartyMessageInformation() {
        return new PartyMessageInformation();
    }

    /**
     * Create an instance of {@link NotionalAmountReference }
     * 
     */
    public NotionalAmountReference createNotionalAmountReference() {
        return new NotionalAmountReference();
    }

    /**
     * Create an instance of {@link ForecastRateIndex }
     * 
     */
    public ForecastRateIndex createForecastRateIndex() {
        return new ForecastRateIndex();
    }

    /**
     * Create an instance of {@link InstrumentId }
     * 
     */
    public InstrumentId createInstrumentId() {
        return new InstrumentId();
    }

    /**
     * Create an instance of {@link AccountId }
     * 
     */
    public AccountId createAccountId() {
        return new AccountId();
    }

    /**
     * Create an instance of {@link StreetAddress }
     * 
     */
    public StreetAddress createStreetAddress() {
        return new StreetAddress();
    }

    /**
     * Create an instance of {@link QuotedCurrencyPair }
     * 
     */
    public QuotedCurrencyPair createQuotedCurrencyPair() {
        return new QuotedCurrencyPair();
    }

    /**
     * Create an instance of {@link ExchangeId }
     * 
     */
    public ExchangeId createExchangeId() {
        return new ExchangeId();
    }

    /**
     * Create an instance of {@link RelativeDateOffset }
     * 
     */
    public RelativeDateOffset createRelativeDateOffset() {
        return new RelativeDateOffset();
    }

    /**
     * Create an instance of {@link Trade }
     * 
     */
    public Trade createTrade() {
        return new Trade();
    }

    /**
     * Create an instance of {@link AllocationCancelled }
     * 
     */
    public AllocationCancelled createAllocationCancelled() {
        return new AllocationCancelled();
    }

    /**
     * Create an instance of {@link NotionalAmount }
     * 
     */
    public NotionalAmount createNotionalAmount() {
        return new NotionalAmount();
    }

    /**
     * Create an instance of {@link Formula }
     * 
     */
    public Formula createFormula() {
        return new Formula();
    }

    /**
     * Create an instance of {@link BusinessDayAdjustments }
     * 
     */
    public BusinessDayAdjustments createBusinessDayAdjustments() {
        return new BusinessDayAdjustments();
    }

    /**
     * Create an instance of {@link InformationProvider }
     * 
     */
    public InformationProvider createInformationProvider() {
        return new InformationProvider();
    }

    /**
     * Create an instance of {@link PartyReference }
     * 
     */
    public PartyReference createPartyReference() {
        return new PartyReference();
    }

    /**
     * Create an instance of {@link FloatingRate }
     * 
     */
    public FloatingRate createFloatingRate() {
        return new FloatingRate();
    }

    /**
     * Create an instance of {@link TradeStatusValue }
     * 
     */
    public TradeStatusValue createTradeStatusValue() {
        return new TradeStatusValue();
    }

    /**
     * Create an instance of {@link ClearanceSystem }
     * 
     */
    public ClearanceSystem createClearanceSystem() {
        return new ClearanceSystem();
    }

    /**
     * Create an instance of {@link TradeHeader }
     * 
     */
    public TradeHeader createTradeHeader() {
        return new TradeHeader();
    }

    /**
     * Create an instance of {@link CashSettlementReferenceBanks }
     * 
     */
    public CashSettlementReferenceBanks createCashSettlementReferenceBanks() {
        return new CashSettlementReferenceBanks();
    }

    /**
     * Create an instance of {@link Frequency }
     * 
     */
    public Frequency createFrequency() {
        return new Frequency();
    }

    /**
     * Create an instance of {@link Novation }
     * 
     */
    public Novation createNovation() {
        return new Novation();
    }

    /**
     * Create an instance of {@link SettlementMethod }
     * 
     */
    public SettlementMethod createSettlementMethod() {
        return new SettlementMethod();
    }

    /**
     * Create an instance of {@link Rounding }
     * 
     */
    public Rounding createRounding() {
        return new Rounding();
    }

    /**
     * Create an instance of {@link AdjustableOrRelativeDate }
     * 
     */
    public AdjustableOrRelativeDate createAdjustableOrRelativeDate() {
        return new AdjustableOrRelativeDate();
    }

    /**
     * Create an instance of {@link Termination }
     * 
     */
    public Termination createTermination() {
        return new Termination();
    }

    /**
     * Create an instance of {@link ReferenceAmount }
     * 
     */
    public ReferenceAmount createReferenceAmount() {
        return new ReferenceAmount();
    }

    /**
     * Create an instance of {@link ContractId }
     * 
     */
    public ContractId createContractId() {
        return new ContractId();
    }

    /**
     * Create an instance of {@link ProblemLocation }
     * 
     */
    public ProblemLocation createProblemLocation() {
        return new ProblemLocation();
    }

    /**
     * Create an instance of {@link Party }
     * 
     */
    public Party createParty() {
        return new Party();
    }

    /**
     * Create an instance of {@link SettlementPriceSource }
     * 
     */
    public SettlementPriceSource createSettlementPriceSource() {
        return new SettlementPriceSource();
    }

    /**
     * Create an instance of {@link MimeType }
     * 
     */
    public MimeType createMimeType() {
        return new MimeType();
    }

    /**
     * Create an instance of {@link FxSpotRateSource }
     * 
     */
    public FxSpotRateSource createFxSpotRateSource() {
        return new FxSpotRateSource();
    }

    /**
     * Create an instance of {@link PositiveStep }
     * 
     */
    public PositiveStep createPositiveStep() {
        return new PositiveStep();
    }

    /**
     * Create an instance of {@link MatrixTerm }
     * 
     */
    public MatrixTerm createMatrixTerm() {
        return new MatrixTerm();
    }

    /**
     * Create an instance of {@link SettlementInstruction }
     * 
     */
    public SettlementInstruction createSettlementInstruction() {
        return new SettlementInstruction();
    }

    /**
     * Create an instance of {@link Step }
     * 
     */
    public Step createStep() {
        return new Step();
    }

    /**
     * Create an instance of {@link ExecutionDateTime }
     * 
     */
    public ExecutionDateTime createExecutionDateTime() {
        return new ExecutionDateTime();
    }

    /**
     * Create an instance of {@link Amendment }
     * 
     */
    public Amendment createAmendment() {
        return new Amendment();
    }

    /**
     * Create an instance of {@link CreditSupportAgreementType }
     * 
     */
    public CreditSupportAgreementType createCreditSupportAgreementType() {
        return new CreditSupportAgreementType();
    }

    /**
     * Create an instance of {@link TradeId }
     * 
     */
    public TradeId createTradeId() {
        return new TradeId();
    }

    /**
     * Create an instance of {@link NonNegativeAmountSchedule }
     * 
     */
    public NonNegativeAmountSchedule createNonNegativeAmountSchedule() {
        return new NonNegativeAmountSchedule();
    }

    /**
     * Create an instance of {@link IntermediaryInformation }
     * 
     */
    public IntermediaryInformation createIntermediaryInformation() {
        return new IntermediaryInformation();
    }

    /**
     * Create an instance of {@link DateReference }
     * 
     */
    public DateReference createDateReference() {
        return new DateReference();
    }

    /**
     * Create an instance of {@link ContractNovation }
     * 
     */
    public ContractNovation createContractNovation() {
        return new ContractNovation();
    }

    /**
     * Create an instance of {@link RequestMessageHeader }
     * 
     */
    public RequestMessageHeader createRequestMessageHeader() {
        return new RequestMessageHeader();
    }

    /**
     * Create an instance of {@link BestFitTrade }
     * 
     */
    public BestFitTrade createBestFitTrade() {
        return new BestFitTrade();
    }

    /**
     * Create an instance of {@link LinkId }
     * 
     */
    public LinkId createLinkId() {
        return new LinkId();
    }

    /**
     * Create an instance of {@link FloatingRateCalculation }
     * 
     */
    public FloatingRateCalculation createFloatingRateCalculation() {
        return new FloatingRateCalculation();
    }

    /**
     * Create an instance of {@link Reason }
     * 
     */
    public Reason createReason() {
        return new Reason();
    }

    /**
     * Create an instance of {@link Strategy }
     * 
     */
    public Strategy createStrategy() {
        return new Strategy();
    }

    /**
     * Create an instance of {@link AllocationAmended }
     * 
     */
    public AllocationAmended createAllocationAmended() {
        return new AllocationAmended();
    }

    /**
     * Create an instance of {@link PositiveMoney }
     * 
     */
    public PositiveMoney createPositiveMoney() {
        return new PositiveMoney();
    }

    /**
     * Create an instance of {@link IdentifiedDate }
     * 
     */
    public IdentifiedDate createIdentifiedDate() {
        return new IdentifiedDate();
    }

    /**
     * Create an instance of {@link AdjustableRelativeOrPeriodicDates2 }
     * 
     */
    public AdjustableRelativeOrPeriodicDates2 createAdjustableRelativeOrPeriodicDates2() {
        return new AdjustableRelativeOrPeriodicDates2();
    }

    /**
     * Create an instance of {@link ConversationId }
     * 
     */
    public ConversationId createConversationId() {
        return new ConversationId();
    }

    /**
     * Create an instance of {@link ProductId }
     * 
     */
    public ProductId createProductId() {
        return new ProductId();
    }

    /**
     * Create an instance of {@link PartialTerminationAmount }
     * 
     */
    public PartialTerminationAmount createPartialTerminationAmount() {
        return new PartialTerminationAmount();
    }

    /**
     * Create an instance of {@link RoutingExplicitDetails }
     * 
     */
    public RoutingExplicitDetails createRoutingExplicitDetails() {
        return new RoutingExplicitDetails();
    }

    /**
     * Create an instance of {@link IdentifiedCurrency }
     * 
     */
    public IdentifiedCurrency createIdentifiedCurrency() {
        return new IdentifiedCurrency();
    }

    /**
     * Create an instance of {@link LegalEntity }
     * 
     */
    public LegalEntity createLegalEntity() {
        return new LegalEntity();
    }

    /**
     * Create an instance of {@link FutureValueAmount }
     * 
     */
    public FutureValueAmount createFutureValueAmount() {
        return new FutureValueAmount();
    }

    /**
     * Create an instance of {@link ExerciseFee }
     * 
     */
    public ExerciseFee createExerciseFee() {
        return new ExerciseFee();
    }

    /**
     * Create an instance of {@link NonNegativeSchedule }
     * 
     */
    public NonNegativeSchedule createNonNegativeSchedule() {
        return new NonNegativeSchedule();
    }

    /**
     * Create an instance of {@link FxCashSettlement }
     * 
     */
    public FxCashSettlement createFxCashSettlement() {
        return new FxCashSettlement();
    }

    /**
     * Create an instance of {@link TradeAlreadyTerminated }
     * 
     */
    public TradeAlreadyTerminated createTradeAlreadyTerminated() {
        return new TradeAlreadyTerminated();
    }

    /**
     * Create an instance of {@link ContractualTermsSupplement }
     * 
     */
    public ContractualTermsSupplement createContractualTermsSupplement() {
        return new ContractualTermsSupplement();
    }

    /**
     * Create an instance of {@link Routing }
     * 
     */
    public Routing createRouting() {
        return new Routing();
    }

    /**
     * Create an instance of {@link SettlementRateSource }
     * 
     */
    public SettlementRateSource createSettlementRateSource() {
        return new SettlementRateSource();
    }

    /**
     * Create an instance of {@link ExerciseFeeSchedule }
     * 
     */
    public ExerciseFeeSchedule createExerciseFeeSchedule() {
        return new ExerciseFeeSchedule();
    }

    /**
     * Create an instance of {@link PrevailingTime }
     * 
     */
    public PrevailingTime createPrevailingTime() {
        return new PrevailingTime();
    }

    /**
     * Create an instance of {@link BlockTradeIdentifier }
     * 
     */
    public BlockTradeIdentifier createBlockTradeIdentifier() {
        return new BlockTradeIdentifier();
    }

    /**
     * Create an instance of {@link LegalEntityReference }
     * 
     */
    public LegalEntityReference createLegalEntityReference() {
        return new LegalEntityReference();
    }

    /**
     * Create an instance of {@link ReturnSwapNotionalAmountReference }
     * 
     */
    public ReturnSwapNotionalAmountReference createReturnSwapNotionalAmountReference() {
        return new ReturnSwapNotionalAmountReference();
    }

    /**
     * Create an instance of {@link Allocation }
     * 
     */
    public Allocation createAllocation() {
        return new Allocation();
    }

    /**
     * Create an instance of {@link NotificationMessageHeader }
     * 
     */
    public NotificationMessageHeader createNotificationMessageHeader() {
        return new NotificationMessageHeader();
    }

    /**
     * Create an instance of {@link BrokerConfirmation }
     * 
     */
    public BrokerConfirmation createBrokerConfirmation() {
        return new BrokerConfirmation();
    }

    /**
     * Create an instance of {@link RateSourcePage }
     * 
     */
    public RateSourcePage createRateSourcePage() {
        return new RateSourcePage();
    }

    /**
     * Create an instance of {@link BusinessCenterTime }
     * 
     */
    public BusinessCenterTime createBusinessCenterTime() {
        return new BusinessCenterTime();
    }

    /**
     * Create an instance of {@link AverageDailyTradingVolumeLimit }
     * 
     */
    public AverageDailyTradingVolumeLimit createAverageDailyTradingVolumeLimit() {
        return new AverageDailyTradingVolumeLimit();
    }

    /**
     * Create an instance of {@link Currency }
     * 
     */
    public Currency createCurrency() {
        return new Currency();
    }

    /**
     * Create an instance of {@link VersionedTradeId }
     * 
     */
    public VersionedTradeId createVersionedTradeId() {
        return new VersionedTradeId();
    }

    /**
     * Create an instance of {@link PartialExercise }
     * 
     */
    public PartialExercise createPartialExercise() {
        return new PartialExercise();
    }

    /**
     * Create an instance of {@link DateRange }
     * 
     */
    public DateRange createDateRange() {
        return new DateRange();
    }

    /**
     * Create an instance of {@link ProductReference }
     * 
     */
    public ProductReference createProductReference() {
        return new ProductReference();
    }

    /**
     * Create an instance of {@link AdjustedRelativeDateOffset }
     * 
     */
    public AdjustedRelativeDateOffset createAdjustedRelativeDateOffset() {
        return new AdjustedRelativeDateOffset();
    }

    /**
     * Create an instance of {@link MessageRejected }
     * 
     */
    public MessageRejected createMessageRejected() {
        return new MessageRejected();
    }

    /**
     * Create an instance of {@link DataDocument }
     * 
     */
    public DataDocument createDataDocument() {
        return new DataDocument();
    }

    /**
     * Create an instance of {@link RoutingId }
     * 
     */
    public RoutingId createRoutingId() {
        return new RoutingId();
    }

    /**
     * Create an instance of {@link EntityName }
     * 
     */
    public EntityName createEntityName() {
        return new EntityName();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link SpreadSchedule }
     * 
     */
    public SpreadSchedule createSpreadSchedule() {
        return new SpreadSchedule();
    }

    /**
     * Create an instance of {@link VersionedContractId }
     * 
     */
    public VersionedContractId createVersionedContractId() {
        return new VersionedContractId();
    }

    /**
     * Create an instance of {@link SimplePayment }
     * 
     */
    public SimplePayment createSimplePayment() {
        return new SimplePayment();
    }

    /**
     * Create an instance of {@link DateOffset }
     * 
     */
    public DateOffset createDateOffset() {
        return new DateOffset();
    }

    /**
     * Create an instance of {@link EuropeanExercise }
     * 
     */
    public EuropeanExercise createEuropeanExercise() {
        return new EuropeanExercise();
    }

    /**
     * Create an instance of {@link FormulaComponent }
     * 
     */
    public FormulaComponent createFormulaComponent() {
        return new FormulaComponent();
    }

    /**
     * Create an instance of {@link MultipleExercise }
     * 
     */
    public MultipleExercise createMultipleExercise() {
        return new MultipleExercise();
    }

    /**
     * Create an instance of {@link PaymentType }
     * 
     */
    public PaymentType createPaymentType() {
        return new PaymentType();
    }

    /**
     * Create an instance of {@link Beneficiary }
     * 
     */
    public Beneficiary createBeneficiary() {
        return new Beneficiary();
    }

    /**
     * Create an instance of {@link MatrixType }
     * 
     */
    public MatrixType createMatrixType() {
        return new MatrixType();
    }

    /**
     * Create an instance of {@link PercentageRule }
     * 
     */
    public PercentageRule createPercentageRule() {
        return new PercentageRule();
    }

    /**
     * Create an instance of {@link AdjustableDatesOrRelativeDateOffset }
     * 
     */
    public AdjustableDatesOrRelativeDateOffset createAdjustableDatesOrRelativeDateOffset() {
        return new AdjustableDatesOrRelativeDateOffset();
    }

    /**
     * Create an instance of {@link FxFixing }
     * 
     */
    public FxFixing createFxFixing() {
        return new FxFixing();
    }

    /**
     * Create an instance of {@link AllocationTradeIdentifier }
     * 
     */
    public AllocationTradeIdentifier createAllocationTradeIdentifier() {
        return new AllocationTradeIdentifier();
    }

    /**
     * Create an instance of {@link EntityId }
     * 
     */
    public EntityId createEntityId() {
        return new EntityId();
    }

    /**
     * Create an instance of {@link AmericanExercise }
     * 
     */
    public AmericanExercise createAmericanExercise() {
        return new AmericanExercise();
    }

    /**
     * Create an instance of {@link ContractualSupplement }
     * 
     */
    public ContractualSupplement createContractualSupplement() {
        return new ContractualSupplement();
    }

    /**
     * Create an instance of {@link PartyTradeIdentifiers }
     * 
     */
    public PartyTradeIdentifiers createPartyTradeIdentifiers() {
        return new PartyTradeIdentifiers();
    }

    /**
     * Create an instance of {@link ExerciseProcedure }
     * 
     */
    public ExerciseProcedure createExerciseProcedure() {
        return new ExerciseProcedure();
    }

    /**
     * Create an instance of {@link EventId }
     * 
     */
    public EventId createEventId() {
        return new EventId();
    }

    /**
     * Create an instance of {@link AdjustableOrRelativeDates }
     * 
     */
    public AdjustableOrRelativeDates createAdjustableOrRelativeDates() {
        return new AdjustableOrRelativeDates();
    }

    /**
     * Create an instance of {@link SettlementInformation }
     * 
     */
    public SettlementInformation createSettlementInformation() {
        return new SettlementInformation();
    }

    /**
     * Create an instance of {@link Increase }
     * 
     */
    public Increase createIncrease() {
        return new Increase();
    }

    /**
     * Create an instance of {@link RoutingIds }
     * 
     */
    public RoutingIds createRoutingIds() {
        return new RoutingIds();
    }

    /**
     * Create an instance of {@link PartyOrAccountReference }
     * 
     */
    public PartyOrAccountReference createPartyOrAccountReference() {
        return new PartyOrAccountReference();
    }

    /**
     * Create an instance of {@link ChangeContractSize }
     * 
     */
    public ChangeContractSize createChangeContractSize() {
        return new ChangeContractSize();
    }

    /**
     * Create an instance of {@link ContractualMatrix }
     * 
     */
    public ContractualMatrix createContractualMatrix() {
        return new ContractualMatrix();
    }

    /**
     * Create an instance of {@link AffectedTransactions }
     * 
     */
    public AffectedTransactions createAffectedTransactions() {
        return new AffectedTransactions();
    }

    /**
     * Create an instance of {@link ContractIdentifier }
     * 
     */
    public ContractIdentifier createContractIdentifier() {
        return new ContractIdentifier();
    }

    /**
     * Create an instance of {@link AdjustableDate }
     * 
     */
    public AdjustableDate createAdjustableDate() {
        return new AdjustableDate();
    }

    /**
     * Create an instance of {@link PositivePayment }
     * 
     */
    public PositivePayment createPositivePayment() {
        return new PositivePayment();
    }

    /**
     * Create an instance of {@link DateTimeList }
     * 
     */
    public DateTimeList createDateTimeList() {
        return new DateTimeList();
    }

    /**
     * Create an instance of {@link IdentifiedPayerReceiver }
     * 
     */
    public IdentifiedPayerReceiver createIdentifiedPayerReceiver() {
        return new IdentifiedPayerReceiver();
    }

    /**
     * Create an instance of {@link MessageAddress }
     * 
     */
    public MessageAddress createMessageAddress() {
        return new MessageAddress();
    }

    /**
     * Create an instance of {@link Exercise }
     * 
     */
    public Exercise createExercise() {
        return new Exercise();
    }

    /**
     * Create an instance of {@link NonNegativePayment }
     * 
     */
    public NonNegativePayment createNonNegativePayment() {
        return new NonNegativePayment();
    }

    /**
     * Create an instance of {@link PricingStructureReference }
     * 
     */
    public PricingStructureReference createPricingStructureReference() {
        return new PricingStructureReference();
    }

    /**
     * Create an instance of {@link TradeAlreadyCancelled }
     * 
     */
    public TradeAlreadyCancelled createTradeAlreadyCancelled() {
        return new TradeAlreadyCancelled();
    }

    /**
     * Create an instance of {@link QueryParameterOperator }
     * 
     */
    public QueryParameterOperator createQueryParameterOperator() {
        return new QueryParameterOperator();
    }

    /**
     * Create an instance of {@link ProductType }
     * 
     */
    public ProductType createProductType() {
        return new ProductType();
    }

    /**
     * Create an instance of {@link Schedule }
     * 
     */
    public Schedule createSchedule() {
        return new Schedule();
    }

    /**
     * Create an instance of {@link Collateral }
     * 
     */
    public Collateral createCollateral() {
        return new Collateral();
    }

    /**
     * Create an instance of {@link Account }
     * 
     */
    public Account createAccount() {
        return new Account();
    }

    /**
     * Create an instance of {@link PositiveAmountSchedule }
     * 
     */
    public PositiveAmountSchedule createPositiveAmountSchedule() {
        return new PositiveAmountSchedule();
    }

    /**
     * Create an instance of {@link InterestAccrualsMethod }
     * 
     */
    public InterestAccrualsMethod createInterestAccrualsMethod() {
        return new InterestAccrualsMethod();
    }

    /**
     * Create an instance of {@link SplitSettlement }
     * 
     */
    public SplitSettlement createSplitSettlement() {
        return new SplitSettlement();
    }

    /**
     * Create an instance of {@link TradeStatusItem }
     * 
     */
    public TradeStatusItem createTradeStatusItem() {
        return new TradeStatusItem();
    }

    /**
     * Create an instance of {@link BermudaExercise }
     * 
     */
    public BermudaExercise createBermudaExercise() {
        return new BermudaExercise();
    }

    /**
     * Create an instance of {@link SpreadScheduleType }
     * 
     */
    public SpreadScheduleType createSpreadScheduleType() {
        return new SpreadScheduleType();
    }

    /**
     * Create an instance of {@link TradeStatus }
     * 
     */
    public TradeStatus createTradeStatus() {
        return new TradeStatus();
    }

    /**
     * Create an instance of {@link SharedAmericanExercise }
     * 
     */
    public SharedAmericanExercise createSharedAmericanExercise() {
        return new SharedAmericanExercise();
    }

    /**
     * Create an instance of {@link MasterAgreementType }
     * 
     */
    public MasterAgreementType createMasterAgreementType() {
        return new MasterAgreementType();
    }

    /**
     * Create an instance of {@link ExerciseNotice }
     * 
     */
    public ExerciseNotice createExerciseNotice() {
        return new ExerciseNotice();
    }

    /**
     * Create an instance of {@link Validation }
     * 
     */
    public Validation createValidation() {
        return new Validation();
    }

    /**
     * Create an instance of {@link ContractHeader }
     * 
     */
    public ContractHeader createContractHeader() {
        return new ContractHeader();
    }

    /**
     * Create an instance of {@link StrikeSchedule }
     * 
     */
    public StrikeSchedule createStrikeSchedule() {
        return new StrikeSchedule();
    }

    /**
     * Create an instance of {@link ReferenceBank }
     * 
     */
    public ReferenceBank createReferenceBank() {
        return new ReferenceBank();
    }

    /**
     * Create an instance of {@link PartyPortfolioName }
     * 
     */
    public PartyPortfolioName createPartyPortfolioName() {
        return new PartyPortfolioName();
    }

    /**
     * Create an instance of {@link TradeAlreadySubmitted }
     * 
     */
    public TradeAlreadySubmitted createTradeAlreadySubmitted() {
        return new TradeAlreadySubmitted();
    }

    /**
     * Create an instance of {@link Offset }
     * 
     */
    public Offset createOffset() {
        return new Offset();
    }

    /**
     * Create an instance of {@link MasterConfirmation }
     * 
     */
    public MasterConfirmation createMasterConfirmation() {
        return new MasterConfirmation();
    }

    /**
     * Create an instance of {@link IndependentAmount }
     * 
     */
    public IndependentAmount createIndependentAmount() {
        return new IndependentAmount();
    }

    /**
     * Create an instance of {@link PartyRole }
     * 
     */
    public PartyRole createPartyRole() {
        return new PartyRole();
    }

    /**
     * Create an instance of {@link QueryParameterId }
     * 
     */
    public QueryParameterId createQueryParameterId() {
        return new QueryParameterId();
    }

    /**
     * Create an instance of {@link OffsetPrevailingTime }
     * 
     */
    public OffsetPrevailingTime createOffsetPrevailingTime() {
        return new OffsetPrevailingTime();
    }

    /**
     * Create an instance of {@link QueryParameter }
     * 
     */
    public QueryParameter createQueryParameter() {
        return new QueryParameter();
    }

    /**
     * Create an instance of {@link AutomaticExercise }
     * 
     */
    public AutomaticExercise createAutomaticExercise() {
        return new AutomaticExercise();
    }

    /**
     * Create an instance of {@link TradeAmendment }
     * 
     */
    public TradeAmendment createTradeAmendment() {
        return new TradeAmendment();
    }

    /**
     * Create an instance of {@link CalculationPeriodFrequency }
     * 
     */
    public CalculationPeriodFrequency createCalculationPeriodFrequency() {
        return new CalculationPeriodFrequency();
    }

    /**
     * Create an instance of {@link PartyId }
     * 
     */
    public PartyId createPartyId() {
        return new PartyId();
    }

    /**
     * Create an instance of {@link Payment }
     * 
     */
    public Payment createPayment() {
        return new Payment();
    }

    /**
     * Create an instance of {@link BusinessCenter }
     * 
     */
    public BusinessCenter createBusinessCenter() {
        return new BusinessCenter();
    }

    /**
     * Create an instance of {@link AllocationCreated }
     * 
     */
    public AllocationCreated createAllocationCreated() {
        return new AllocationCreated();
    }

    /**
     * Create an instance of {@link DateList }
     * 
     */
    public DateList createDateList() {
        return new DateList();
    }

    /**
     * Create an instance of {@link AdjustableRelativeOrPeriodicDates }
     * 
     */
    public AdjustableRelativeOrPeriodicDates createAdjustableRelativeOrPeriodicDates() {
        return new AdjustableRelativeOrPeriodicDates();
    }

    /**
     * Create an instance of {@link PartyTradeIdentifier }
     * 
     */
    public PartyTradeIdentifier createPartyTradeIdentifier() {
        return new PartyTradeIdentifier();
    }

    /**
     * Create an instance of {@link ReasonCode }
     * 
     */
    public ReasonCode createReasonCode() {
        return new ReasonCode();
    }

    /**
     * Create an instance of {@link BrokerConfirmationType }
     * 
     */
    public BrokerConfirmationType createBrokerConfirmationType() {
        return new BrokerConfirmationType();
    }

    /**
     * Create an instance of {@link DayCountFraction }
     * 
     */
    public DayCountFraction createDayCountFraction() {
        return new DayCountFraction();
    }

    /**
     * Create an instance of {@link TradeSide }
     * 
     */
    public TradeSide createTradeSide() {
        return new TradeSide();
    }

    /**
     * Create an instance of {@link IdentifiedCurrencyReference }
     * 
     */
    public IdentifiedCurrencyReference createIdentifiedCurrencyReference() {
        return new IdentifiedCurrencyReference();
    }

    /**
     * Create an instance of {@link MultipleExchangeAnnex }
     * 
     */
    public MultipleExchangeAnnex createMultipleExchangeAnnex() {
        return new MultipleExchangeAnnex();
    }

    /**
     * Create an instance of {@link AdjustableOrRelativeAndAdjustedDate }
     * 
     */
    public AdjustableOrRelativeAndAdjustedDate createAdjustableOrRelativeAndAdjustedDate() {
        return new AdjustableOrRelativeAndAdjustedDate();
    }

    /**
     * Create an instance of {@link MasterAgreement }
     * 
     */
    public MasterAgreement createMasterAgreement() {
        return new MasterAgreement();
    }

    /**
     * Create an instance of {@link PeriodicDates }
     * 
     */
    public PeriodicDates createPeriodicDates() {
        return new PeriodicDates();
    }

    /**
     * Create an instance of {@link TradeDifference }
     * 
     */
    public TradeDifference createTradeDifference() {
        return new TradeDifference();
    }

    /**
     * Create an instance of {@link CorrespondentInformation }
     * 
     */
    public CorrespondentInformation createCorrespondentInformation() {
        return new CorrespondentInformation();
    }

    /**
     * Create an instance of {@link SettlementPriceDefaultElection }
     * 
     */
    public SettlementPriceDefaultElection createSettlementPriceDefaultElection() {
        return new SettlementPriceDefaultElection();
    }

    /**
     * Create an instance of {@link CreditSeniority }
     * 
     */
    public CreditSeniority createCreditSeniority() {
        return new CreditSeniority();
    }

    /**
     * Create an instance of {@link Approvals }
     * 
     */
    public Approvals createApprovals() {
        return new Approvals();
    }

    /**
     * Create an instance of {@link Math }
     * 
     */
    public Math createMath() {
        return new Math();
    }

    /**
     * Create an instance of {@link ScheduleReference }
     * 
     */
    public ScheduleReference createScheduleReference() {
        return new ScheduleReference();
    }

    /**
     * Create an instance of {@link ReferenceBankId }
     * 
     */
    public ReferenceBankId createReferenceBankId() {
        return new ReferenceBankId();
    }

    /**
     * Create an instance of {@link MasterAgreementVersion }
     * 
     */
    public MasterAgreementVersion createMasterAgreementVersion() {
        return new MasterAgreementVersion();
    }

    /**
     * Create an instance of {@link PortfolioName }
     * 
     */
    public PortfolioName createPortfolioName() {
        return new PortfolioName();
    }

    /**
     * Create an instance of {@link RequestTradeStatus }
     * 
     */
    public RequestTradeStatus createRequestTradeStatus() {
        return new RequestTradeStatus();
    }

    /**
     * Create an instance of {@link Period }
     * 
     */
    public Period createPeriod() {
        return new Period();
    }

    /**
     * Create an instance of {@link Documentation }
     * 
     */
    public Documentation createDocumentation() {
        return new Documentation();
    }

    /**
     * Create an instance of {@link NonNegativeStep }
     * 
     */
    public NonNegativeStep createNonNegativeStep() {
        return new NonNegativeStep();
    }

    /**
     * Create an instance of {@link InterpolationMethod }
     * 
     */
    public InterpolationMethod createInterpolationMethod() {
        return new InterpolationMethod();
    }

    /**
     * Create an instance of {@link RoutingIdsAndExplicitDetails }
     * 
     */
    public RoutingIdsAndExplicitDetails createRoutingIdsAndExplicitDetails() {
        return new RoutingIdsAndExplicitDetails();
    }

    /**
     * Create an instance of {@link CreditDerivativesNotices }
     * 
     */
    public CreditDerivativesNotices createCreditDerivativesNotices() {
        return new CreditDerivativesNotices();
    }

    /**
     * Create an instance of {@link NotionalReference }
     * 
     */
    public NotionalReference createNotionalReference() {
        return new NotionalReference();
    }

    /**
     * Create an instance of {@link MasterConfirmationType }
     * 
     */
    public MasterConfirmationType createMasterConfirmationType() {
        return new MasterConfirmationType();
    }

    /**
     * Create an instance of {@link FirstPeriodStartDate }
     * 
     */
    public FirstPeriodStartDate createFirstPeriodStartDate() {
        return new FirstPeriodStartDate();
    }

    /**
     * Create an instance of {@link FxRate }
     * 
     */
    public FxRate createFxRate() {
        return new FxRate();
    }

    /**
     * Create an instance of {@link MasterConfirmationAnnexType }
     * 
     */
    public MasterConfirmationAnnexType createMasterConfirmationAnnexType() {
        return new MasterConfirmationAnnexType();
    }

    /**
     * Create an instance of {@link InterestAccrualsCompoundingMethod }
     * 
     */
    public InterestAccrualsCompoundingMethod createInterestAccrualsCompoundingMethod() {
        return new InterestAccrualsCompoundingMethod();
    }

    /**
     * Create an instance of {@link DeterminationMethodReference }
     * 
     */
    public DeterminationMethodReference createDeterminationMethodReference() {
        return new DeterminationMethodReference();
    }

    /**
     * Create an instance of {@link BusinessDateRange }
     * 
     */
    public BusinessDateRange createBusinessDateRange() {
        return new BusinessDateRange();
    }

    /**
     * Create an instance of {@link Stub }
     * 
     */
    public Stub createStub() {
        return new Stub();
    }

    /**
     * Create an instance of {@link ManualExercise }
     * 
     */
    public ManualExercise createManualExercise() {
        return new ManualExercise();
    }

    /**
     * Create an instance of {@link BusinessDayAdjustmentsReference }
     * 
     */
    public BusinessDayAdjustmentsReference createBusinessDayAdjustmentsReference() {
        return new BusinessDayAdjustmentsReference();
    }

    /**
     * Create an instance of {@link MainPublication }
     * 
     */
    public MainPublication createMainPublication() {
        return new MainPublication();
    }

    /**
     * Create an instance of {@link ContractReference }
     * 
     */
    public ContractReference createContractReference() {
        return new ContractReference();
    }

    /**
     * Create an instance of {@link AdditionalData }
     * 
     */
    public AdditionalData createAdditionalData() {
        return new AdditionalData();
    }

    /**
     * Create an instance of {@link ContractualDefinitions }
     * 
     */
    public ContractualDefinitions createContractualDefinitions() {
        return new ContractualDefinitions();
    }

    /**
     * Create an instance of {@link FloatingRateIndex }
     * 
     */
    public FloatingRateIndex createFloatingRateIndex() {
        return new FloatingRateIndex();
    }

    /**
     * Create an instance of {@link StubValue }
     * 
     */
    public StubValue createStubValue() {
        return new StubValue();
    }

    /**
     * Create an instance of {@link NonNegativeMoney }
     * 
     */
    public NonNegativeMoney createNonNegativeMoney() {
        return new NonNegativeMoney();
    }

    /**
     * Create an instance of {@link ResetFrequency }
     * 
     */
    public ResetFrequency createResetFrequency() {
        return new ResetFrequency();
    }

    /**
     * Create an instance of {@link PartyOrTradeSideReference }
     * 
     */
    public PartyOrTradeSideReference createPartyOrTradeSideReference() {
        return new PartyOrTradeSideReference();
    }

    /**
     * Create an instance of {@link Approval }
     * 
     */
    public Approval createApproval() {
        return new Approval();
    }

    /**
     * Create an instance of {@link AdjustableDates }
     * 
     */
    public AdjustableDates createAdjustableDates() {
        return new AdjustableDates();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Exercise }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fpml.org/2009/FpML-4-7", name = "exercise")
    public JAXBElement<Exercise> createExercise(Exercise value) {
        return new JAXBElement<Exercise>(_Exercise_QNAME, Exercise.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AmericanExercise }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fpml.org/2009/FpML-4-7", name = "americanExercise", substitutionHeadNamespace = "http://www.fpml.org/2009/FpML-4-7", substitutionHeadName = "exercise")
    public JAXBElement<AmericanExercise> createAmericanExercise(AmericanExercise value) {
        return new JAXBElement<AmericanExercise>(_AmericanExercise_QNAME, AmericanExercise.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Event }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fpml.org/2009/FpML-4-7", name = "event")
    public JAXBElement<Event> createEvent(Event value) {
        return new JAXBElement<Event>(_Event_QNAME, Event.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BermudaExercise }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fpml.org/2009/FpML-4-7", name = "bermudaExercise", substitutionHeadNamespace = "http://www.fpml.org/2009/FpML-4-7", substitutionHeadName = "exercise")
    public JAXBElement<BermudaExercise> createBermudaExercise(BermudaExercise value) {
        return new JAXBElement<BermudaExercise>(_BermudaExercise_QNAME, BermudaExercise.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EuropeanExercise }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fpml.org/2009/FpML-4-7", name = "europeanExercise", substitutionHeadNamespace = "http://www.fpml.org/2009/FpML-4-7", substitutionHeadName = "exercise")
    public JAXBElement<EuropeanExercise> createEuropeanExercise(EuropeanExercise value) {
        return new JAXBElement<EuropeanExercise>(_EuropeanExercise_QNAME, EuropeanExercise.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Strategy }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fpml.org/2009/FpML-4-7", name = "strategy", substitutionHeadNamespace = "http://www.fpml.org/2009/FpML-4-7", substitutionHeadName = "product")
    public JAXBElement<Strategy> createStrategy(Strategy value) {
        return new JAXBElement<Strategy>(_Strategy_QNAME, Strategy.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Product }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fpml.org/2009/FpML-4-7", name = "product")
    public JAXBElement<Product> createProduct(Product value) {
        return new JAXBElement<Product>(_Product_QNAME, Product.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PartyReference }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fpml.org/2009/FpML-4-7", name = "remainingParty", scope = Novation.class)
    public JAXBElement<PartyReference> createNovationRemainingParty(PartyReference value) {
        return new JAXBElement<PartyReference>(_NovationRemainingParty_QNAME, PartyReference.class, Novation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FirstPeriodStartDate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fpml.org/2009/FpML-4-7", name = "firstPeriodStartDate", scope = Novation.class)
    public JAXBElement<FirstPeriodStartDate> createNovationFirstPeriodStartDate(FirstPeriodStartDate value) {
        return new JAXBElement<FirstPeriodStartDate>(_NovationFirstPeriodStartDate_QNAME, FirstPeriodStartDate.class, Novation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PartyReference }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fpml.org/2009/FpML-4-7", name = "transferee", scope = Novation.class)
    public JAXBElement<PartyReference> createNovationTransferee(PartyReference value) {
        return new JAXBElement<PartyReference>(_NovationTransferee_QNAME, PartyReference.class, Novation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PartyReference }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fpml.org/2009/FpML-4-7", name = "otherRemainingParty", scope = Novation.class)
    public JAXBElement<PartyReference> createNovationOtherRemainingParty(PartyReference value) {
        return new JAXBElement<PartyReference>(_NovationOtherRemainingParty_QNAME, PartyReference.class, Novation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PartyTradeIdentifiers }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fpml.org/2009/FpML-4-7", name = "newTransactionReference", scope = Novation.class)
    public JAXBElement<PartyTradeIdentifiers> createNovationNewTransactionReference(PartyTradeIdentifiers value) {
        return new JAXBElement<PartyTradeIdentifiers>(_NovationNewTransactionReference_QNAME, PartyTradeIdentifiers.class, Novation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PartyTradeIdentifiers }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fpml.org/2009/FpML-4-7", name = "oldTransactionReference", scope = Novation.class)
    public JAXBElement<PartyTradeIdentifiers> createNovationOldTransactionReference(PartyTradeIdentifiers value) {
        return new JAXBElement<PartyTradeIdentifiers>(_NovationOldTransactionReference_QNAME, PartyTradeIdentifiers.class, Novation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fpml.org/2009/FpML-4-7", name = "novationDate", scope = Novation.class)
    public JAXBElement<XMLGregorianCalendar> createNovationNovationDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_NovationNovationDate_QNAME, XMLGregorianCalendar.class, Novation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Payment }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fpml.org/2009/FpML-4-7", name = "payment", scope = Novation.class)
    public JAXBElement<Payment> createNovationPayment(Payment value) {
        return new JAXBElement<Payment>(_NovationPayment_QNAME, Payment.class, Novation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fpml.org/2009/FpML-4-7", name = "novationTradeDate", scope = Novation.class)
    public JAXBElement<XMLGregorianCalendar> createNovationNovationTradeDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_NovationNovationTradeDate_QNAME, XMLGregorianCalendar.class, Novation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Trade }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fpml.org/2009/FpML-4-7", name = "oldTransaction", scope = Novation.class)
    public JAXBElement<Trade> createNovationOldTransaction(Trade value) {
        return new JAXBElement<Trade>(_NovationOldTransaction_QNAME, Trade.class, Novation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Trade }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fpml.org/2009/FpML-4-7", name = "newTransaction", scope = Novation.class)
    public JAXBElement<Trade> createNovationNewTransaction(Trade value) {
        return new JAXBElement<Trade>(_NovationNewTransaction_QNAME, Trade.class, Novation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Empty }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fpml.org/2009/FpML-4-7", name = "nonReliance", scope = Novation.class)
    public JAXBElement<Empty> createNovationNonReliance(Empty value) {
        return new JAXBElement<Empty>(_NovationNonReliance_QNAME, Empty.class, Novation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContractualSupplement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fpml.org/2009/FpML-4-7", name = "contractualSupplement", scope = Novation.class)
    public JAXBElement<ContractualSupplement> createNovationContractualSupplement(ContractualSupplement value) {
        return new JAXBElement<ContractualSupplement>(_NovationContractualSupplement_QNAME, ContractualSupplement.class, Novation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PartyReference }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fpml.org/2009/FpML-4-7", name = "transferor", scope = Novation.class)
    public JAXBElement<PartyReference> createNovationTransferor(PartyReference value) {
        return new JAXBElement<PartyReference>(_NovationTransferor_QNAME, PartyReference.class, Novation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fpml.org/2009/FpML-4-7", name = "novatedNumberOfOptions", scope = Novation.class)
    public JAXBElement<BigDecimal> createNovationNovatedNumberOfOptions(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_NovationNovatedNumberOfOptions_QNAME, BigDecimal.class, Novation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Trade }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fpml.org/2009/FpML-4-7", name = "remainingTrade", scope = Novation.class)
    public JAXBElement<Trade> createNovationRemainingTrade(Trade value) {
        return new JAXBElement<Trade>(_NovationRemainingTrade_QNAME, Trade.class, Novation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContractualTermsSupplement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fpml.org/2009/FpML-4-7", name = "contractualTermsSupplement", scope = Novation.class)
    public JAXBElement<ContractualTermsSupplement> createNovationContractualTermsSupplement(ContractualTermsSupplement value) {
        return new JAXBElement<ContractualTermsSupplement>(_NovationContractualTermsSupplement_QNAME, ContractualTermsSupplement.class, Novation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContractualDefinitions }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fpml.org/2009/FpML-4-7", name = "contractualDefinitions", scope = Novation.class)
    public JAXBElement<ContractualDefinitions> createNovationContractualDefinitions(ContractualDefinitions value) {
        return new JAXBElement<ContractualDefinitions>(_NovationContractualDefinitions_QNAME, ContractualDefinitions.class, Novation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fpml.org/2009/FpML-4-7", name = "fullFirstCalculationPeriod", scope = Novation.class)
    public JAXBElement<Boolean> createNovationFullFirstCalculationPeriod(Boolean value) {
        return new JAXBElement<Boolean>(_NovationFullFirstCalculationPeriod_QNAME, Boolean.class, Novation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreditDerivativesNotices }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fpml.org/2009/FpML-4-7", name = "creditDerivativesNotices", scope = Novation.class)
    public JAXBElement<CreditDerivativesNotices> createNovationCreditDerivativesNotices(CreditDerivativesNotices value) {
        return new JAXBElement<CreditDerivativesNotices>(_NovationCreditDerivativesNotices_QNAME, CreditDerivativesNotices.class, Novation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Money }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fpml.org/2009/FpML-4-7", name = "novatedAmount", scope = Novation.class)
    public JAXBElement<Money> createNovationNovatedAmount(Money value) {
        return new JAXBElement<Money>(_NovationNovatedAmount_QNAME, Money.class, Novation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EntityId }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fpml.org/2009/FpML-4-7", name = "entityId", scope = LegalEntity.class)
    public JAXBElement<EntityId> createLegalEntityEntityId(EntityId value) {
        return new JAXBElement<EntityId>(_LegalEntityEntityId_QNAME, EntityId.class, LegalEntity.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EntityName }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fpml.org/2009/FpML-4-7", name = "entityName", scope = LegalEntity.class)
    public JAXBElement<EntityName> createLegalEntityEntityName(EntityName value) {
        return new JAXBElement<EntityName>(_LegalEntityEntityName_QNAME, EntityName.class, LegalEntity.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fpml.org/2009/FpML-4-7", name = "accountName", scope = Account.class)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createAccountAccountName(String value) {
        return new JAXBElement<String>(_AccountAccountName_QNAME, String.class, Account.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AccountId }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fpml.org/2009/FpML-4-7", name = "accountId", scope = Account.class)
    public JAXBElement<AccountId> createAccountAccountId(AccountId value) {
        return new JAXBElement<AccountId>(_AccountAccountId_QNAME, AccountId.class, Account.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PartyReference }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fpml.org/2009/FpML-4-7", name = "remainingParty", scope = ContractNovation.class)
    public JAXBElement<PartyReference> createContractNovationRemainingParty(PartyReference value) {
        return new JAXBElement<PartyReference>(_NovationRemainingParty_QNAME, PartyReference.class, ContractNovation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FirstPeriodStartDate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fpml.org/2009/FpML-4-7", name = "firstPeriodStartDate", scope = ContractNovation.class)
    public JAXBElement<FirstPeriodStartDate> createContractNovationFirstPeriodStartDate(FirstPeriodStartDate value) {
        return new JAXBElement<FirstPeriodStartDate>(_NovationFirstPeriodStartDate_QNAME, FirstPeriodStartDate.class, ContractNovation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fpml.org/2009/FpML-4-7", name = "novationContractDate", scope = ContractNovation.class)
    public JAXBElement<XMLGregorianCalendar> createContractNovationNovationContractDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_ContractNovationNovationContractDate_QNAME, XMLGregorianCalendar.class, ContractNovation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PartyReference }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fpml.org/2009/FpML-4-7", name = "otherRemainingParty", scope = ContractNovation.class)
    public JAXBElement<PartyReference> createContractNovationOtherRemainingParty(PartyReference value) {
        return new JAXBElement<PartyReference>(_NovationOtherRemainingParty_QNAME, PartyReference.class, ContractNovation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PartyReference }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fpml.org/2009/FpML-4-7", name = "transferee", scope = ContractNovation.class)
    public JAXBElement<PartyReference> createContractNovationTransferee(PartyReference value) {
        return new JAXBElement<PartyReference>(_NovationTransferee_QNAME, PartyReference.class, ContractNovation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Contract }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fpml.org/2009/FpML-4-7", name = "oldContract", scope = ContractNovation.class)
    public JAXBElement<Contract> createContractNovationOldContract(Contract value) {
        return new JAXBElement<Contract>(_ContractNovationOldContract_QNAME, Contract.class, ContractNovation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fpml.org/2009/FpML-4-7", name = "novationDate", scope = ContractNovation.class)
    public JAXBElement<XMLGregorianCalendar> createContractNovationNovationDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_NovationNovationDate_QNAME, XMLGregorianCalendar.class, ContractNovation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Payment }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fpml.org/2009/FpML-4-7", name = "payment", scope = ContractNovation.class)
    public JAXBElement<Payment> createContractNovationPayment(Payment value) {
        return new JAXBElement<Payment>(_NovationPayment_QNAME, Payment.class, ContractNovation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Empty }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fpml.org/2009/FpML-4-7", name = "nonReliance", scope = ContractNovation.class)
    public JAXBElement<Empty> createContractNovationNonReliance(Empty value) {
        return new JAXBElement<Empty>(_NovationNonReliance_QNAME, Empty.class, ContractNovation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContractReference }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fpml.org/2009/FpML-4-7", name = "oldContractReference", scope = ContractNovation.class)
    public JAXBElement<ContractReference> createContractNovationOldContractReference(ContractReference value) {
        return new JAXBElement<ContractReference>(_ContractNovationOldContractReference_QNAME, ContractReference.class, ContractNovation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PartyReference }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fpml.org/2009/FpML-4-7", name = "transferor", scope = ContractNovation.class)
    public JAXBElement<PartyReference> createContractNovationTransferor(PartyReference value) {
        return new JAXBElement<PartyReference>(_NovationTransferor_QNAME, PartyReference.class, ContractNovation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fpml.org/2009/FpML-4-7", name = "novatedNumberOfOptions", scope = ContractNovation.class)
    public JAXBElement<BigDecimal> createContractNovationNovatedNumberOfOptions(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_NovationNovatedNumberOfOptions_QNAME, BigDecimal.class, ContractNovation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContractualTermsSupplement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fpml.org/2009/FpML-4-7", name = "contractualTermsSupplement", scope = ContractNovation.class)
    public JAXBElement<ContractualTermsSupplement> createContractNovationContractualTermsSupplement(ContractualTermsSupplement value) {
        return new JAXBElement<ContractualTermsSupplement>(_NovationContractualTermsSupplement_QNAME, ContractualTermsSupplement.class, ContractNovation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContractReference }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fpml.org/2009/FpML-4-7", name = "newContractReference", scope = ContractNovation.class)
    public JAXBElement<ContractReference> createContractNovationNewContractReference(ContractReference value) {
        return new JAXBElement<ContractReference>(_ContractNovationNewContractReference_QNAME, ContractReference.class, ContractNovation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContractualDefinitions }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fpml.org/2009/FpML-4-7", name = "contractualDefinitions", scope = ContractNovation.class)
    public JAXBElement<ContractualDefinitions> createContractNovationContractualDefinitions(ContractualDefinitions value) {
        return new JAXBElement<ContractualDefinitions>(_NovationContractualDefinitions_QNAME, ContractualDefinitions.class, ContractNovation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fpml.org/2009/FpML-4-7", name = "fullFirstCalculationPeriod", scope = ContractNovation.class)
    public JAXBElement<Boolean> createContractNovationFullFirstCalculationPeriod(Boolean value) {
        return new JAXBElement<Boolean>(_NovationFullFirstCalculationPeriod_QNAME, Boolean.class, ContractNovation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fpml.org/2009/FpML-4-7", name = "novatedNumberOfUnits", scope = ContractNovation.class)
    public JAXBElement<BigDecimal> createContractNovationNovatedNumberOfUnits(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_ContractNovationNovatedNumberOfUnits_QNAME, BigDecimal.class, ContractNovation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreditDerivativesNotices }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fpml.org/2009/FpML-4-7", name = "creditDerivativesNotices", scope = ContractNovation.class)
    public JAXBElement<CreditDerivativesNotices> createContractNovationCreditDerivativesNotices(CreditDerivativesNotices value) {
        return new JAXBElement<CreditDerivativesNotices>(_NovationCreditDerivativesNotices_QNAME, CreditDerivativesNotices.class, ContractNovation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Contract }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fpml.org/2009/FpML-4-7", name = "newContract", scope = ContractNovation.class)
    public JAXBElement<Contract> createContractNovationNewContract(Contract value) {
        return new JAXBElement<Contract>(_ContractNovationNewContract_QNAME, Contract.class, ContractNovation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Money }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fpml.org/2009/FpML-4-7", name = "novatedAmount", scope = ContractNovation.class)
    public JAXBElement<Money> createContractNovationNovatedAmount(Money value) {
        return new JAXBElement<Money>(_NovationNovatedAmount_QNAME, Money.class, ContractNovation.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdjustableDate2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fpml.org/2009/FpML-4-7", name = "adjustablePaymentDate", scope = PaymentDetail.class)
    public JAXBElement<AdjustableDate2> createPaymentDetailAdjustablePaymentDate(AdjustableDate2 value) {
        return new JAXBElement<AdjustableDate2>(_PaymentDetailAdjustablePaymentDate_QNAME, AdjustableDate2 .class, PaymentDetail.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fpml.org/2009/FpML-4-7", name = "adjustedPaymentDate", scope = PaymentDetail.class)
    public JAXBElement<XMLGregorianCalendar> createPaymentDetailAdjustedPaymentDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_PaymentDetailAdjustedPaymentDate_QNAME, XMLGregorianCalendar.class, PaymentDetail.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdjustableOrRelativeDate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fpml.org/2009/FpML-4-7", name = "paymentDate", scope = PaymentDetail.class)
    public JAXBElement<AdjustableOrRelativeDate> createPaymentDetailPaymentDate(AdjustableOrRelativeDate value) {
        return new JAXBElement<AdjustableOrRelativeDate>(_PaymentDetailPaymentDate_QNAME, AdjustableOrRelativeDate.class, PaymentDetail.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Money }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fpml.org/2009/FpML-4-7", name = "paymentAmount", scope = PaymentDetail.class)
    public JAXBElement<Money> createPaymentDetailPaymentAmount(Money value) {
        return new JAXBElement<Money>(_PaymentDetailPaymentAmount_QNAME, Money.class, PaymentDetail.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PaymentRule }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fpml.org/2009/FpML-4-7", name = "paymentRule", scope = PaymentDetail.class)
    public JAXBElement<PaymentRule> createPaymentDetailPaymentRule(PaymentRule value) {
        return new JAXBElement<PaymentRule>(_PaymentDetailPaymentRule_QNAME, PaymentRule.class, PaymentDetail.class, value);
    }

}
