//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.16 at 08:54:24 PM EDT 
//


package org.fpml._2009.fpml_4_7;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A type for defining PrePayment.
 * 
 * <p>Java class for PrePayment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PrePayment">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.fpml.org/2009/FpML-4-7}PaymentBase">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.fpml.org/2009/FpML-4-7}PayerReceiver.model"/>
 *         &lt;element name="prePayment" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="prePaymentAmount" type="{http://www.fpml.org/2009/FpML-4-7}Money"/>
 *         &lt;element name="prePaymentDate" type="{http://www.fpml.org/2009/FpML-4-7}AdjustableDate"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PrePayment", propOrder = {
    "payerPartyReference",
    "receiverPartyReference",
    "prePayment",
    "prePaymentAmount",
    "prePaymentDate"
})
public class PrePayment
    extends PaymentBase
{

    @XmlElement(required = true)
    protected PartyOrAccountReference payerPartyReference;
    @XmlElement(required = true)
    protected PartyOrAccountReference receiverPartyReference;
    protected boolean prePayment;
    @XmlElement(required = true)
    protected Money prePaymentAmount;
    @XmlElement(required = true)
    protected AdjustableDate prePaymentDate;

    /**
     * Gets the value of the payerPartyReference property.
     * 
     * @return
     *     possible object is
     *     {@link PartyOrAccountReference }
     *     
     */
    public PartyOrAccountReference getPayerPartyReference() {
        return payerPartyReference;
    }

    /**
     * Sets the value of the payerPartyReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartyOrAccountReference }
     *     
     */
    public void setPayerPartyReference(PartyOrAccountReference value) {
        this.payerPartyReference = value;
    }

    /**
     * Gets the value of the receiverPartyReference property.
     * 
     * @return
     *     possible object is
     *     {@link PartyOrAccountReference }
     *     
     */
    public PartyOrAccountReference getReceiverPartyReference() {
        return receiverPartyReference;
    }

    /**
     * Sets the value of the receiverPartyReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartyOrAccountReference }
     *     
     */
    public void setReceiverPartyReference(PartyOrAccountReference value) {
        this.receiverPartyReference = value;
    }

    /**
     * Gets the value of the prePayment property.
     * 
     */
    public boolean isPrePayment() {
        return prePayment;
    }

    /**
     * Sets the value of the prePayment property.
     * 
     */
    public void setPrePayment(boolean value) {
        this.prePayment = value;
    }

    /**
     * Gets the value of the prePaymentAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Money }
     *     
     */
    public Money getPrePaymentAmount() {
        return prePaymentAmount;
    }

    /**
     * Sets the value of the prePaymentAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Money }
     *     
     */
    public void setPrePaymentAmount(Money value) {
        this.prePaymentAmount = value;
    }

    /**
     * Gets the value of the prePaymentDate property.
     * 
     * @return
     *     possible object is
     *     {@link AdjustableDate }
     *     
     */
    public AdjustableDate getPrePaymentDate() {
        return prePaymentDate;
    }

    /**
     * Sets the value of the prePaymentDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdjustableDate }
     *     
     */
    public void setPrePaymentDate(AdjustableDate value) {
        this.prePaymentDate = value;
    }

}
