//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.16 at 08:54:11 PM EDT 
//


package org.fpml._2009.fpml_4_7;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * A notice used to notify changes in the pricing of a given facility.
 * 
 * <p>Java class for PricingChangeNotice complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PricingChangeNotice">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.fpml.org/2009/FpML-4-7}FacilityNotice">
 *       &lt;sequence>
 *         &lt;element name="pricingChangeReason" type="{http://www.fpml.org/2009/FpML-4-7}PricingChangeReason" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element name="marginRateChange" type="{http://www.fpml.org/2009/FpML-4-7}MarginRateChange" maxOccurs="unbounded"/>
 *             &lt;element name="onGoingFeeRateChange" type="{http://www.fpml.org/2009/FpML-4-7}OnGoingFeeRateChange" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;/sequence>
 *           &lt;element name="onGoingFeeRateChange" type="{http://www.fpml.org/2009/FpML-4-7}OnGoingFeeRateChange" maxOccurs="unbounded"/>
 *         &lt;/choice>
 *         &lt;element name="party" type="{http://www.fpml.org/2009/FpML-4-7}Party" maxOccurs="unbounded" minOccurs="2"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PricingChangeNotice", propOrder = {
    "rest"
})
public class PricingChangeNotice
    extends FacilityNotice
{

    @XmlElementRefs({
        @XmlElementRef(name = "marginRateChange", namespace = "http://www.fpml.org/2009/FpML-4-7", type = JAXBElement.class),
        @XmlElementRef(name = "onGoingFeeRateChange", namespace = "http://www.fpml.org/2009/FpML-4-7", type = JAXBElement.class),
        @XmlElementRef(name = "pricingChangeReason", namespace = "http://www.fpml.org/2009/FpML-4-7", type = JAXBElement.class),
        @XmlElementRef(name = "party", namespace = "http://www.fpml.org/2009/FpML-4-7", type = JAXBElement.class)
    })
    protected List<JAXBElement<?>> rest;

    /**
     * Gets the rest of the content model. 
     * 
     * <p>
     * You are getting this "catch-all" property because of the following reason: 
     * The field name "OnGoingFeeRateChange" is used by two different parts of a schema. See: 
     * line 1161 of file:/C:/MyWorkspaces/TestWorkspace/JaxbBuilder/schema/FpML%20Schemas/fpml-loan-4-7.xsd
     * line 1155 of file:/C:/MyWorkspaces/TestWorkspace/JaxbBuilder/schema/FpML%20Schemas/fpml-loan-4-7.xsd
     * <p>
     * To get rid of this property, apply a property customization to one 
     * of both of the following declarations to change their names: 
     * Gets the value of the rest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link OnGoingFeeRateChange }{@code >}
     * {@link JAXBElement }{@code <}{@link MarginRateChange }{@code >}
     * {@link JAXBElement }{@code <}{@link PricingChangeReason }{@code >}
     * {@link JAXBElement }{@code <}{@link Party }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getRest() {
        if (rest == null) {
            rest = new ArrayList<JAXBElement<?>>();
        }
        return this.rest;
    }

}
