//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.16 at 08:53:22 PM EDT 
//


package org.fpml._2009.fpml_4_7;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A type that represents a single exchange of one currency for another that may be quoted on. The definition allows currency amounts to be absent and does not include an exchange rate.
 * 
 * <p>Java class for QuotableFxLeg complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QuotableFxLeg">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.fpml.org/2009/FpML-4-7}QuotableProduct">
 *       &lt;sequence>
 *         &lt;element name="exchangedCurrency" type="{http://www.fpml.org/2009/FpML-4-7}QuotablePayment" minOccurs="0"/>
 *         &lt;element name="exchangeRate" type="{http://www.fpml.org/2009/FpML-4-7}QuotableFxRate"/>
 *         &lt;element name="nonDeliverableForward" type="{http://www.fpml.org/2009/FpML-4-7}FxCashSettlement" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QuotableFxLeg", propOrder = {
    "exchangedCurrency",
    "exchangeRate",
    "nonDeliverableForward"
})
public class QuotableFxLeg
    extends QuotableProduct
{

    protected QuotablePayment exchangedCurrency;
    @XmlElement(required = true)
    protected QuotableFxRate exchangeRate;
    protected FxCashSettlement nonDeliverableForward;

    /**
     * Gets the value of the exchangedCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link QuotablePayment }
     *     
     */
    public QuotablePayment getExchangedCurrency() {
        return exchangedCurrency;
    }

    /**
     * Sets the value of the exchangedCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuotablePayment }
     *     
     */
    public void setExchangedCurrency(QuotablePayment value) {
        this.exchangedCurrency = value;
    }

    /**
     * Gets the value of the exchangeRate property.
     * 
     * @return
     *     possible object is
     *     {@link QuotableFxRate }
     *     
     */
    public QuotableFxRate getExchangeRate() {
        return exchangeRate;
    }

    /**
     * Sets the value of the exchangeRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuotableFxRate }
     *     
     */
    public void setExchangeRate(QuotableFxRate value) {
        this.exchangeRate = value;
    }

    /**
     * Gets the value of the nonDeliverableForward property.
     * 
     * @return
     *     possible object is
     *     {@link FxCashSettlement }
     *     
     */
    public FxCashSettlement getNonDeliverableForward() {
        return nonDeliverableForward;
    }

    /**
     * Sets the value of the nonDeliverableForward property.
     * 
     * @param value
     *     allowed object is
     *     {@link FxCashSettlement }
     *     
     */
    public void setNonDeliverableForward(FxCashSettlement value) {
        this.nonDeliverableForward = value;
    }

}
