//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.16 at 08:53:15 PM EDT 
//


package org.fpml._2009.fpml_4_7;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * A definition of the positions that are requested.
 * 
 * <p>Java class for RequestedPositions complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RequestedPositions">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="queryPortfolio" type="{http://www.fpml.org/2009/FpML-4-7}QueryPortfolio"/>
 *         &lt;group ref="{http://www.fpml.org/2009/FpML-4-7}PositionIdAndVersion.model"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RequestedPositions", propOrder = {
    "queryPortfolio",
    "positionId",
    "version"
})
public class RequestedPositions {

    protected QueryPortfolio queryPortfolio;
    protected PositionId positionId;
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger version;

    /**
     * Gets the value of the queryPortfolio property.
     * 
     * @return
     *     possible object is
     *     {@link QueryPortfolio }
     *     
     */
    public QueryPortfolio getQueryPortfolio() {
        return queryPortfolio;
    }

    /**
     * Sets the value of the queryPortfolio property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueryPortfolio }
     *     
     */
    public void setQueryPortfolio(QueryPortfolio value) {
        this.queryPortfolio = value;
    }

    /**
     * Gets the value of the positionId property.
     * 
     * @return
     *     possible object is
     *     {@link PositionId }
     *     
     */
    public PositionId getPositionId() {
        return positionId;
    }

    /**
     * Sets the value of the positionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link PositionId }
     *     
     */
    public void setPositionId(PositionId value) {
        this.positionId = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVersion(BigInteger value) {
        this.version = value;
    }

}
