//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.16 at 08:54:20 PM EDT 
//


package org.fpml._2009.fpml_4_7;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A type that is used for including rates against base currency for non-base currency FX contracts.
 * 
 * <p>Java class for SideRates complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SideRates">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="baseCurrency" type="{http://www.fpml.org/2009/FpML-4-7}Currency"/>
 *         &lt;element name="currency1SideRate" type="{http://www.fpml.org/2009/FpML-4-7}SideRate" minOccurs="0"/>
 *         &lt;element name="currency2SideRate" type="{http://www.fpml.org/2009/FpML-4-7}SideRate" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SideRates", propOrder = {
    "baseCurrency",
    "currency1SideRate",
    "currency2SideRate"
})
public class SideRates {

    @XmlElement(required = true)
    protected Currency baseCurrency;
    protected SideRate currency1SideRate;
    protected SideRate currency2SideRate;

    /**
     * Gets the value of the baseCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link Currency }
     *     
     */
    public Currency getBaseCurrency() {
        return baseCurrency;
    }

    /**
     * Sets the value of the baseCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link Currency }
     *     
     */
    public void setBaseCurrency(Currency value) {
        this.baseCurrency = value;
    }

    /**
     * Gets the value of the currency1SideRate property.
     * 
     * @return
     *     possible object is
     *     {@link SideRate }
     *     
     */
    public SideRate getCurrency1SideRate() {
        return currency1SideRate;
    }

    /**
     * Sets the value of the currency1SideRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link SideRate }
     *     
     */
    public void setCurrency1SideRate(SideRate value) {
        this.currency1SideRate = value;
    }

    /**
     * Gets the value of the currency2SideRate property.
     * 
     * @return
     *     possible object is
     *     {@link SideRate }
     *     
     */
    public SideRate getCurrency2SideRate() {
        return currency2SideRate;
    }

    /**
     * Sets the value of the currency2SideRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link SideRate }
     *     
     */
    public void setCurrency2SideRate(SideRate value) {
        this.currency2SideRate = value;
    }

}
