//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.16 at 08:55:21 PM EDT 
//


package org.fpml._2009.fpml_4_7;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * The parties to the trade form into sides. Each side has defined roles in the lifecyle of the trade fulfilled by parties. Each party role is given in the likely order they would be filled during the lifecycle of a trade.
 * 
 * <p>Java class for TradeSide complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TradeSide">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="orderer" type="{http://www.fpml.org/2009/FpML-4-7}PartyRole" minOccurs="0"/>
 *         &lt;element name="introducer" type="{http://www.fpml.org/2009/FpML-4-7}PartyRole" minOccurs="0"/>
 *         &lt;element name="executor" type="{http://www.fpml.org/2009/FpML-4-7}PartyRole" minOccurs="0"/>
 *         &lt;element name="confirmer" type="{http://www.fpml.org/2009/FpML-4-7}PartyRole" minOccurs="0"/>
 *         &lt;element name="creditor" type="{http://www.fpml.org/2009/FpML-4-7}PartyRole"/>
 *         &lt;element name="calculater" type="{http://www.fpml.org/2009/FpML-4-7}PartyRole" minOccurs="0"/>
 *         &lt;element name="settler" type="{http://www.fpml.org/2009/FpML-4-7}PartyRole" minOccurs="0"/>
 *         &lt;element name="beneficiary" type="{http://www.fpml.org/2009/FpML-4-7}PartyRole" minOccurs="0"/>
 *         &lt;element name="accountant" type="{http://www.fpml.org/2009/FpML-4-7}PartyRole" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TradeSide", propOrder = {
    "orderer",
    "introducer",
    "executor",
    "confirmer",
    "creditor",
    "calculater",
    "settler",
    "beneficiary",
    "accountant"
})
public class TradeSide {

    protected PartyRole orderer;
    protected PartyRole introducer;
    protected PartyRole executor;
    protected PartyRole confirmer;
    @XmlElement(required = true)
    protected PartyRole creditor;
    protected PartyRole calculater;
    protected PartyRole settler;
    protected PartyRole beneficiary;
    protected List<PartyRole> accountant;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Gets the value of the orderer property.
     * 
     * @return
     *     possible object is
     *     {@link PartyRole }
     *     
     */
    public PartyRole getOrderer() {
        return orderer;
    }

    /**
     * Sets the value of the orderer property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartyRole }
     *     
     */
    public void setOrderer(PartyRole value) {
        this.orderer = value;
    }

    /**
     * Gets the value of the introducer property.
     * 
     * @return
     *     possible object is
     *     {@link PartyRole }
     *     
     */
    public PartyRole getIntroducer() {
        return introducer;
    }

    /**
     * Sets the value of the introducer property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartyRole }
     *     
     */
    public void setIntroducer(PartyRole value) {
        this.introducer = value;
    }

    /**
     * Gets the value of the executor property.
     * 
     * @return
     *     possible object is
     *     {@link PartyRole }
     *     
     */
    public PartyRole getExecutor() {
        return executor;
    }

    /**
     * Sets the value of the executor property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartyRole }
     *     
     */
    public void setExecutor(PartyRole value) {
        this.executor = value;
    }

    /**
     * Gets the value of the confirmer property.
     * 
     * @return
     *     possible object is
     *     {@link PartyRole }
     *     
     */
    public PartyRole getConfirmer() {
        return confirmer;
    }

    /**
     * Sets the value of the confirmer property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartyRole }
     *     
     */
    public void setConfirmer(PartyRole value) {
        this.confirmer = value;
    }

    /**
     * Gets the value of the creditor property.
     * 
     * @return
     *     possible object is
     *     {@link PartyRole }
     *     
     */
    public PartyRole getCreditor() {
        return creditor;
    }

    /**
     * Sets the value of the creditor property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartyRole }
     *     
     */
    public void setCreditor(PartyRole value) {
        this.creditor = value;
    }

    /**
     * Gets the value of the calculater property.
     * 
     * @return
     *     possible object is
     *     {@link PartyRole }
     *     
     */
    public PartyRole getCalculater() {
        return calculater;
    }

    /**
     * Sets the value of the calculater property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartyRole }
     *     
     */
    public void setCalculater(PartyRole value) {
        this.calculater = value;
    }

    /**
     * Gets the value of the settler property.
     * 
     * @return
     *     possible object is
     *     {@link PartyRole }
     *     
     */
    public PartyRole getSettler() {
        return settler;
    }

    /**
     * Sets the value of the settler property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartyRole }
     *     
     */
    public void setSettler(PartyRole value) {
        this.settler = value;
    }

    /**
     * Gets the value of the beneficiary property.
     * 
     * @return
     *     possible object is
     *     {@link PartyRole }
     *     
     */
    public PartyRole getBeneficiary() {
        return beneficiary;
    }

    /**
     * Sets the value of the beneficiary property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartyRole }
     *     
     */
    public void setBeneficiary(PartyRole value) {
        this.beneficiary = value;
    }

    /**
     * Gets the value of the accountant property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the accountant property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAccountant().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PartyRole }
     * 
     * 
     */
    public List<PartyRole> getAccountant() {
        if (accountant == null) {
            accountant = new ArrayList<PartyRole>();
        }
        return this.accountant;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
