//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.16 at 08:52:39 PM EDT 
//


package org.fpml._2009.fpml_4_7;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A Variance Swap.
 * 
 * <p>Java class for VarianceSwap complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VarianceSwap">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.fpml.org/2009/FpML-4-7}NettedSwapBase">
 *       &lt;sequence>
 *         &lt;element name="varianceLeg" type="{http://www.fpml.org/2009/FpML-4-7}VarianceLeg" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VarianceSwap", propOrder = {
    "varianceLeg"
})
public class VarianceSwap
    extends NettedSwapBase
{

    @XmlElement(required = true)
    protected List<VarianceLeg> varianceLeg;

    /**
     * Gets the value of the varianceLeg property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the varianceLeg property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVarianceLeg().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VarianceLeg }
     * 
     * 
     */
    public List<VarianceLeg> getVarianceLeg() {
        if (varianceLeg == null) {
            varianceLeg = new ArrayList<VarianceLeg>();
        }
        return this.varianceLeg;
    }

}
