//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.06 at 08:25:04 PM EDT 
//


package org.mpilone.spring.web.domain.messages;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.mpilone.spring.web.domain.messages package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.mpilone.spring.web.domain.messages
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ConvertTemperatureResponse }
     * 
     */
    public ConvertTemperatureResponse createConvertTemperatureResponse() {
        return new ConvertTemperatureResponse();
    }

    /**
     * Create an instance of {@link SaveWeatherUpdateResponse }
     * 
     */
    public SaveWeatherUpdateResponse createSaveWeatherUpdateResponse() {
        return new SaveWeatherUpdateResponse();
    }

    /**
     * Create an instance of {@link GetWeatherReportResponse }
     * 
     */
    public GetWeatherReportResponse createGetWeatherReportResponse() {
        return new GetWeatherReportResponse();
    }

    /**
     * Create an instance of {@link ConvertTemperature }
     * 
     */
    public ConvertTemperature createConvertTemperature() {
        return new ConvertTemperature();
    }

    /**
     * Create an instance of {@link SaveWeatherUpdate }
     * 
     */
    public SaveWeatherUpdate createSaveWeatherUpdate() {
        return new SaveWeatherUpdate();
    }

    /**
     * Create an instance of {@link GetWeatherReport }
     * 
     */
    public GetWeatherReport createGetWeatherReport() {
        return new GetWeatherReport();
    }

}
